### ISSUE TITLE
Error on installing TH++ (fblualib)

### ISSUE THREAD

**Issue by rudrapoudel** [facebook/fbcunn#10]
Hi there,

I have encountered following error while installing fblualib (Ubuntu 14.04,  GCC 4.8.2). For me this looks error on downloading the file from googlecode. I have searched around and also done following things but no luck.

This is the actual error:
Error: curl: (77) error setting certificate verify locations: CAfile: /etc/pki/tls/certs/ca-bundle.crt

This is what I tried:
1. ca-certificates is upto date: sudo apt-get install ca-certificates
2. Some forum suggested: echo tlsv1 > $HOME/.curlrc
3. Ubuntu don't have certificate with that name so: sudo cp /etc/pki/nssdb/cert9.db /etc/pki/tls/certs/ca-bundle.crt
4. We already running curl in insecure mode (with option -sk), however also tried with sudo

Installation log:
------------
Installing TH++

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

Installing FBLuaLib

-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Folly: /usr/local/include  
-- Found Glog: /usr/include  
-- Found Torch7 in /home/rp14/libraries/torch-distro/install
-- REQUIRED_ARGS (missing:  THPP_INCLUDE_DIR THPP_LIBRARIES) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
THPP_INCLUDE_DIR
   used as include directory in directory /tmp/fblualib-build.q5zMgI/fblualib/fblualib
THPP_LIBRARY
    linked by target "fblualib" in directory /tmp/fblualib-build.q5zMgI/fblualib/fblualib

-- Configuring incomplete, errors occurred!
See also "/tmp/fblualib-build.q5zMgI/fblualib/fblualib/build/CMakeFiles/CMakeOutput.log".

All done!

**Comment by rudrapoudel** [comment]
My above guess was correct, this is how I solved it,

Change following line from ../thpp/build.sh,
curl -JLO https://googletest.googlecode.com/files/gtest-1.7.0.zip

to,
curl -k -JLO https://googletest.googlecode.com/files/gtest-1.7.0.zip

I am closing this bug here because I assume this should be something to do with THPP not fbcunn!

**Comment by Tgaaly** [comment]
I have the same problem on Ubuntu 14.04 and these steps did not solve the problem for me. Any ideas?

```
make[2]: Leaving directory `/tmp/fblualib-build.9gmIZV/fbthrift/thrift'
make[1]: Leaving directory `/tmp/fblualib-build.9gmIZV/fbthrift/thrift'
+ echo

+ echo 'Installing TH++'
Installing TH++
+ echo

+ cd /tmp/fblualib-build.9gmIZV/thpp/thpp
+ ./build.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

```

**Comment by Tgaaly** [comment]
I was able to install by manually following the install_all.sh steps
In build.sh for thpp I added "curl -sk ..." - this fixed the problem above

but when I reached running the build.sh of fblualib
I got the following error. I am sure that luarocks is installed because I can run it from the command line. 

```
sudo ./build.sh 
-- Found Folly: /usr/local/include  
-- Found Torch7 in /home/tarek/Libraries/torch/install
-- Found Folly: /usr/local/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tarek/Libraries/fblualib/fblualib/build
[100%] Built target fblualib
[100%] Built target fblualib
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libfblualib.so
-- Up-to-date: /usr/local/include/fblualib/LuaUtils.h
-- Up-to-date: /usr/local/include/fblualib/LuaUtils-inl.h
./build.sh: line 33: luarocks: command not found
sudo: luarocks: command not found
```

Running luarocks from the terminal gives me the following:

```
luarocks

LuaRocks 2.2.0beta1, a module deployment system for Lua

```

**Comment by Tgaaly** [comment]
I fixed this issue by again manually doing the steps in the fblualib/build.sh 
```
luarocks make rockspec/fb$rock-$version.rockspec || sudo luarocks make rockspec/fb$rock-$version.rockspec
```

Now back to square 1 with this error:

```
CMake Error at CMakeLists.txt:25 (FIND_PACKAGE):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/tarek/Libraries/fblualib/fblualib/mattorch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

```
