### ISSUE TITLE
Invalid data in manifest file for module nn.THNN (invalid data for nn scm-1)

### ISSUE THREAD

**Issue by vgprasadh** [facebook/fbcunn#102]
Hi,

I hit the following issue: 

/home/prasad/torch/torch-distro/install/bin/luajit: .../torch/torch-distro/install/share/lua/5.1/trepl/init.lua:384: .../torch/torch-distro/install/share/lua/5.1/trepl/init.lua:384: .../torch/torch-distro/install/share/lua/5.1/trepl/init.lua:384: ...h/torch-distro/install/share/lua/5.1/luarocks/loader.lua:154: Invalid data in manifest file for module nn.THNN (invalid data for nn scm-1)
stack traceback:
        [C]: in function 'error'
        .../torch/torch-distro/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
        test_DataParallelComprehensive.lua:4: in main chunk
        [C]: in function 'dofile'
        ...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x10005b80

Tried the solution of https://github.com/facebook/fbcunn/issues/13 but still hitting the same issue.

Any thoughts ?

Thanks
Prasad.

**Comment by vgprasadh** [comment]
BTW - "luarocks show nn | grep -i THNN" doesn't show anything at all. With the latest nn from this repo does show the nn.THNN but then I run into the optim problem described https://github.com/facebook/fbnn/issues/4 

Any help would be appreciated.

**Comment by soumith** [comment]
nn's getParamsByDevice branch was behind the master by quite a bit, which is why you see this error. Now this should be fixed, just rebased that branch.
