### ISSUE TITLE
Question: does fbfft have any dependencies on anything besides CUDA compiler/driver?

### ISSUE THREAD

**Issue by hughperkins** [facebook/fbcunn#103]
Hi,

I know I'm being kind of lazy here, but ... does fbfft have any dependencies on anything besides the CUDA compiler/driver?  For example, the 'Torch (native)' convolutional implementation uses im2col followed by SGEMM on cublas, and therefore has a dependency on cublas.  'Torch (native)' is therefore not easily portable to OpenCL, unless there is an equivalent implementation of cublas on OpenCL, which there kind of is, but performance of 'Torch (native)' is heavily dependent on the performacne of the underlying blas implementation.  What about fbfft?  By the way, I know I'm being lazy again, what is the license of fbfft?  Is it compatible with eg BSDv2?  What is the reason that 'Torch (native)' is not currently using fbfft, but im2col over cublas?

**Comment by hughperkins** [comment]
Whats the 'patent grant' bit mean?  What is included?  What is not?  Is there anything that a company using an OpenCL port of fbfft might be potentially concerned about and / or need to consider and potentially seek legal advice on?

**Comment by hughperkins** [comment]
Hmmm, seems fft has `cublas` in headers, so ... does depend on a blas implementation? 

https://github.com/facebook/fbcunn/blob/master/src/fft/CuFFTConvolution.cuh#L9
```
#include <cublas_v2.h>
```

**Comment by soumith** [comment]
fbfft depended / depends on a blas implementation for some code paths. @nicolasvasilache eventually wrote his own gemm because cuBLAS was being a bit of a bottleneck for the problem / transpose types.

**Comment by hughperkins** [comment]
> @nicolasvasilache eventually wrote his own gemm

Interesting.  Is the gemm generally available?  What geometries does the gemm work effectively on?

**Comment by soumith** [comment]
Yes, the MM is part of https://github.com/facebook/fbcuda and https://github.com/facebook/fbcunn/blob/master/src/MM.cu

The sizes for which it performs well is very very specific to FFT convolutions. Dropping an email to Nicolas is probably more effective than github
