### ISSUE TITLE
Compatibility for 10.10.2+

### ISSUE THREAD

**Issue by shyamalschandra** [facebook/fbcunn#12]
Hi,

When will there be compatibility with 10.10.2+ because that is a major problem due to the lack of CUDA support with virtualization of Ub. 14.10+ on VirtualBox?

Thanks!

**Comment by soumith** [comment]
We are working on this, I expect in about 1 month. We are creating folly binaries for OSX and Linux.

**Comment by shyamalschandra** [comment]
Thank you.  I just started downloading the version.
