### ISSUE TITLE
DataParallel and ModelParallel need to use CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by rudrapoudel** [facebook/fbcunn#15]
Hi there,

My server has device id 1= K40, 2= Quadro, and 3= K40, so when I set device id 1 and 3 for data parallel,

```
local amodel = nn.Sequential():add(features):add(classifier)
model = nn.DataParallel(1)
...
model:add(amodel:clone(), opt.gpuids[i])
 ```
using 2 gpus, it gives following error,  

```
/home/rp14/libraries/torch-distro/install/bin/luajit: ...ries/torch-distro/install/share/lua/5.1/cutorch/init.lua:19: /usr/local/share/lua/5.1/fbcunn/AbstractParallel.lua:162: assertion failed!
stack traceback:
	[C]: in function 'error'
	...ries/torch-distro/install/share/lua/5.1/cutorch/init.lua:19: in function 'withDevice'
	/usr/local/share/lua/5.1/fbcunn/AbstractParallel.lua:161: in function 'forward'
	...raries/torch-distro/install/share/lua/5.1/fbnn/Optim.lua:144: in function 'optimize'
	./train.lua:156: in function 'f2'
	/home/rp14/dnn/data.lua:33: in function 'addjob'
	./train.lua:102: in function 'miniBatchSGD'
	./train.lua:72: in function 'train'
	main.lua:61: in main chunk
	[C]: in function 'dofile'
	...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00405940
```

**Comment by soumith** [comment]
you could try this:
CUDA_VISIBLE_DEVICES=0,2 th [your-script]

That way, it is masked at a process level, torch only sees two GPUs overall.

**Comment by tudor** [comment]
Yes, known issue. You should use CUDA_VISIBLE_DEVICES to select the set of
GPUs to run on. There are a few hidden assumptions that the GPU ids are
contiguous starting at 0 (1 in Torch-land).

-Tudor.

**Comment by ajtulloch** [comment]
Is it worth adding an `assert` somewhere in `AbstractParallel` to enforce the Lua `gpuid`'s are contiguous from 1?

**Comment by rudrapoudel** [comment]
Thanks!

I got a new error now. Looks there is a some **memory overhead** problem with the data parallel as the code runs completly fine with the one gpu.  Why would that be so? Following is the only changes in the code,
```
  local model
  if nGPU >1 then
    local amodel = nn.Sequential():add(features):add(classifier)
    model = nn.DataParallel(1)
    for i = 1,nGPU do
      if i == 1 then
          model:add(amodel)
      else
          model:add(amodel:clone())
      end
    end
  else
    model = nn.Sequential():add(features):add(classifier)
  end
```
**Rest is EXACTLY same**. Please, let me know if I am missing something. 

Here is the error,

```
/home/rp14/libraries/torch-distro/install/bin/luajit: ...ries/torch-distro/install/share/lua/5.1/cutorch/init.lua:19: /tmp/luarocks_cutorch-scm-1-9199/cutorch/lib/THC/THCStorage.cu(29) : cuda runtime error : out of memory
stack traceback:
	[C]: in function 'error'
	...ries/torch-distro/install/share/lua/5.1/cutorch/init.lua:19: in function 'withDevice'
	/usr/local/share/lua/5.1/fbcunn/DataParallel.lua:132: in function '_combine_gradients'
	/usr/local/share/lua/5.1/fbcunn/DataParallel.lua:164: in function 'fun'
	...braries/torch-distro/install/share/lua/5.1/pl/tablex.lua:423: in function 'foreachi'
	/usr/local/share/lua/5.1/fbcunn/DataParallel.lua:116: in function '_mixGrads'
	...raries/torch-distro/install/share/lua/5.1/fbnn/Optim.lua:153: in function 'optimize'
	./train.lua:156: in function 'f2'
	/home/rp14/dnn/data.lua:33: in function 'addjob'
	./train.lua:102: in function 'miniBatchSGD'
	./train.lua:72: in function 'train'
	main.lua:61: in main chunk
	[C]: in function 'dofile'
	...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00405940
```

**Comment by soumith** [comment]
umm, because you are adding as many "amodel" to your network as the number of GPUs.
You can keep model exactly as it is every for multi-GPU data-parallel, i.e.

model = nn.Sequential():add(features):add(classifier)
model = nn.DataParallel(1):add(model)

That's it, you dont need anything else.

**Comment by rudrapoudel** [comment]
If I do the way you said then time for one K40 and two K40 is the same for example from imagenet/models/overfeat_cudnn.lua. Also, please note that *updateX* functions in DataParallel and AbstractParallel iterate over number of *modules*, which could be only added via *XParallel:add* method. Hence, the way I added the model in DataParallel looks logical.

One working example would be really helpful!

Many thanks for awesome library and support!

**Comment by soumith** [comment]
Ok will post a DataParallel example in the next couple of days

**Comment by mmmikael** [comment]
For some reason, there is a speed-up if ```nn.DataParallel``` includes only the feature part. Training runs about 1.6x faster with 2 GPUs on my machine (2xGTX 970) with that code:
```lua
   -- 1.4. Combine 1.2 and 1.3 to produce final model
   local model
   if nGPU == 1 then
      model = nn.Sequential():add(features):add(classifier)
   elseif nGPU == 2 then
      -- Parallelize 'features' only
      local features2 = nn.DataParallel(1)
      features2:add(features)
      features2:add(features:clone())
      model = nn.Sequential():add(features2):add(classifier)
   end
```

**Comment by rudrapoudel** [comment]
Thank you so much guys, now it is working like charm!

Example code,
```
if opt.num_gpu > 1 then
  print('Using data parallel')
  local gpu_net = nn.DataParallel(1):cuda()
  for i = 1, opt.num_gpu do
    local cur_gpu = math.fmod(opt.gpuid + (i-1)-1, cutorch.getDeviceCount())+1
    cutorch.setDevice(cur_gpu)
    gpu_net:add(model:clone():cuda(), cur_gpu)
  end
  cutorch.setDevice(opt.gpuid)

  model = gpu_net
end
```
