### ISSUE TITLE
Problem in CMake dependency file discovery leading to build failure

### ISSUE THREAD

**Issue by jmtrenkle** [facebook/fbcunn#16]
We have attempted to build the fbcunn addition to Torch on a pristine Ubuntu instance in EC2 completely from scratch as well as on a pre-loaded AMI.  Both attempts have led to a failure when invoking the luarrocks command (below).

The instance info: Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-44-generic x86_64).

For sanity, we've gone through the install process individually and together, but the results are the same.  We attempted to determine in which configure file we could insert the location of the missing includes, but to no avail. We would appreciate any insights that would get us up and running with your significant contributions to Deep Learning,

Thanks

=------ Log -------
> luarocks make rocks/fbcunn-scm-1.rockspec

yields the following log output:

   git submodule init
   git submodule update
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/ubuntu/torch-distro/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/ubuntu/torch-distro/install/lib/luarocks/rocks/fbcunn/scm-1"

-- Found Torch7 in /home/ubuntu/torch-distro/install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/FAIR/fbcunn/build
cd build && make install
[  2%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/cuda/fft/./fbcunnlayers_cuda_generated_CuFFTConvolution_UpdateGradInput.cu.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

-- This repeats for most targets and then terminates as follows: --

Scanning dependencies of target fbcunnlayers_cuda
[ 44%] Building CXX object CMakeFiles/fbcunnlayers_cuda.dir/src/cuda/util/Misc.cpp.o
[ 47%] Building CXX object CMakeFiles/fbcunnlayers_cuda.dir/src/cuda/fft/CuFFTConvolution.cpp.o
In file included from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cuh:12:0,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.h:5,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cpp:3:
/home/ubuntu/FAIR/fbcunn/src/cuda/fft/Utils-inl.h: In function ‘std::unique_ptr<THCudaTensor, CudaTensorDeleter> facebook::deeplearning::torch::makeCuFFTTensorReal(THCudaTensor*, const std::vector<long int>&, THCudaTensor*, facebook::deeplearning::torch::FFTOutputSpecification)’:
/home/ubuntu/FAIR/fbcunn/src/cuda/fft/Utils-inl.h:26:48: error: too many arguments to function ‘int THCudaTensor_nDimension(const THCudaTensor*)’
   DCHECK_EQ(4, THCudaTensor_nDimension(NULL, in));
                                                ^
In file included from /home/ubuntu/torch-distro/install/include/THC/THCGeneral.h:4:0,
                 from /home/ubuntu/torch-distro/install/include/THC/THC.h:4,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cuh:6,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.h:5,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cpp:3:
/home/ubuntu/torch-distro/install/include/TH/THTensor.h:8:39: note: declared here
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                                       ^
/home/ubuntu/torch-distro/install/include/TH/THGeneral.h:70:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/home/ubuntu/torch-distro/install/include/TH/THTensor.h:8:27: note: in expansion of macro ‘TH_CONCAT_4’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                           ^
/home/ubuntu/torch-distro/install/include/TH/generic/THTensor.h:27:12: note: in expansion of macro ‘THTensor_’
 TH_API int THTensor_(nDimension)(const THTensor *self);
            ^
In file included from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/Utils.h:83:0,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cpp:12:
/home/ubuntu/FAIR/fbcunn/src/cuda/fft/Utils-inl.h:36:54: error: too many arguments to function ‘long int THCudaTensor_size(const THCudaTensor*, int)’
   auto batchOrFFTDim0 = THCudaTensor_size(NULL, in, 0); // always batch
                                                      ^
In file included from /home/ubuntu/torch-distro/install/include/THC/THCGeneral.h:4:0,
                 from /home/ubuntu/torch-distro/install/include/THC/THC.h:4,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cuh:6,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.h:5,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cpp:3:
/home/ubuntu/torch-distro/install/include/TH/THTensor.h:8:39: note: declared here
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                                       ^
/home/ubuntu/torch-distro/install/include/TH/THGeneral.h:70:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/home/ubuntu/torch-distro/install/include/TH/THTensor.h:8:27: note: in expansion of macro ‘TH_CONCAT_4’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                           ^
/home/ubuntu/torch-distro/install/include/TH/generic/THTensor.h:28:13: note: in expansion of macro ‘THTensor_’
 TH_API long THTensor_(size)(const THTensor *self, int dim);
             ^
In file included from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/Utils.h:83:0,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cpp:12:
/home/ubuntu/FAIR/fbcunn/src/cuda/fft/Utils-inl.h:41:51: error: too many arguments to function ‘long int THCudaTensor_size(const THCudaTensor*, int)’
     batchOrFFTDim1 = THCudaTensor_size(NULL, in, 1);
                                                   ^
In file included from /home/ubuntu/torch-distro/install/include/THC/THCGeneral.h:4:0,
                 from /home/ubuntu/torch-distro/install/include/THC/THC.h:4,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cuh:6,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.h:5,
                 from /home/ubuntu/FAIR/fbcunn/src/cuda/fft/CuFFTConvolution.cpp:3:
/home/ubuntu/torch-distro/install/include/TH/THTensor.h:8:39: note: declared here
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                                       ^
/home/ubuntu/torch-distro/install/include/TH/THGeneral.h:70:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w

and much more...

**Comment by jmtrenkle** [comment]
Forgot to mention that the instance type is g2.2xlarge

**Comment by soumith** [comment]
this error is because your cutorch lags behind master by a week or so.

A recent change to cutorch changes the THC C API significantly, and fbcunn was updated to use the new cutorch API via this commit: https://github.com/facebook/fbcunn/pull/14. The torch distro was also updated appropriately, and fbcunn INSTALL instructions were also updated to point to the correct location via this commit: https://github.com/facebook/fbcunn/commit/50436639b3496a1b721cd29e1857821f6bb725a6

To fix this issue, simply reinstall cutorch/cunn:
luarocks install cutorch
luarocks install cunn

and then reinstall fbcunn

luarocks make rocks/fbcunn-scm-1.rockspec

Alternatively,
do: rm -rf ~/torch-distro and reinstall the torch distro freshly using https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-torch-in-a-local-folder

**Comment by jmtrenkle** [comment]
Thanks for your rapid response on this issue.  It seems to have built properly now.  Apparently the dependency issue was a red herring.  Thanks again for contributing to the community -- I'm sure we'll get a lot of mileage out of your work.
