### ISSUE TITLE
Results for examples/imagenet?

### ISSUE THREAD

**Issue by kmatzen** [facebook/fbcunn#17]
Do you have any results for your imagenet examples that you'd be willing to share?  For example, final model snapshots or training logs?

**Comment by soumith** [comment]
Sure, why not. I'll try to prep something next week, when i get back to a work computer.

**Comment by soumith** [comment]
Was on vacation, sorry for delay.
Here is the full log for overfeat:
https://gist.github.com/soumith/d364081b2fa70f8cc307

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
