### ISSUE TITLE
ModelParallel not working

### ISSUE THREAD

**Issue by omkarparkhi** [facebook/fbcunn#22]
Hi,

I am running the AlexNet cudnn training example on Ubuntu 14.04 and getting this error
after mean image is computed.

torch/fbcunn/examples/imagenet/models/alexnet_cudnn.lua:8: attempt to call field 'ModelParallel' (a nil value)
stack traceback:
	.../torch/fbcunn/examples/imagenet/models/alexnet_cudnn.lua:8: in function 'createModel'
	/home/omkar/torch/fbcunn/examples/imagenet/model.lua:25: in main chunk
	[C]: in function 'dofile'
	main.lua:29: in main chunk
	[C]: in function 'dofile'
	...mkar/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406170

**Comment by soumith** [comment]
fixed now in master. there was a missing "require"
