### ISSUE TITLE
Warning: cannot write object field <*Desc>

### ISSUE THREAD

**Issue by keven425** [facebook/fbcunn#25]
I get a bunch of following errors when trying to write model. I'm running the example in cudnn mode. When I sanitize the model using this: https://gist.github.com/szagoruyko/b6e70f6c6be9a8399c10 , the warnings went away, but the resulting model.t7 file is empty.

Any ideas?

$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <algType>
$ Warning: cannot write object field <weightDesc>
$ Warning: cannot write object field <biasDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <convDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <poolDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <algType>
$ Warning: cannot write object field <weightDesc>
$ Warning: cannot write object field <biasDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <convDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <poolDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <algType>
$ Warning: cannot write object field <weightDesc>
$ Warning: cannot write object field <biasDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <convDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <algType>
$ Warning: cannot write object field <weightDesc>
$ Warning: cannot write object field <biasDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <convDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <poolDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <algType>
$ Warning: cannot write object field <weightDesc>
$ Warning: cannot write object field <biasDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <convDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <poolDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <algType>
$ Warning: cannot write object field <weightDesc>
$ Warning: cannot write object field <biasDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <convDesc>
$ Warning: cannot write object field <iDesc>

**Comment by soumith** [comment]
use this snippet to sanitize your model, that version looks buggy:
```lua
   function removeDescriptors(net)
      net:for_each(function (val)
                      if torch.type(val):find('cudnn') then
                         for name,field in pairs(val) do
                            if torch.type(field) == 'cdata' then
                               val[name] = nil
                            end
                         end
                      end
                   end)
   end
```

Either ways the warning are harmless.

I just tested that this function works properly and saves the model correctly.

**Comment by soumith** [comment]
Added a model sanitizer to the example by default: https://github.com/facebook/fbcunn/commit/de2fd6ddb3bdb67bf4d314411ebcb6072b0645ea

**Comment by keven425** [comment]
@soumith thanks for the reply!

I'm still getting an empty model.t7 after using this new function. Any ideas?

ls kevenet\,nEpochs\=1/\,SatFeb2802\:23\:182015/ -l
total 24
-rw-r--r-- 1 root root 5812 Feb 28 02:23 classes.t7
-rw-r--r-- 1 root root    4 Feb 28 02:26 model_1.t7
-rw-r--r-- 1 root root  169 Feb 28 02:26 optimState_1.t7
-rw-r--r-- 1 root root  140 Feb 28 02:26 test.log
-rw-r--r-- 1 root root  115 Feb 28 02:26 train.log
root@keven4255:~/fbcunn_imagenet/imagenet_runs#

**Comment by soumith** [comment]
i have no idea why you're getting an empty model. did you modify the example, or are you reporting out-of-the-box behavior?

**Comment by keven425** [comment]
It's likely an issue on my end. I did modify the example model. I will look into it. Thanks!
