### ISSUE TITLE
commit required for fbcunn doesn't include bug fix in Modules.lua

### ISSUE THREAD

**Issue by jonathantompson** [facebook/fbcunn#26]
This issue is strictly for the getParamsByDevice branch of nn.  I figured since it's a fbcunn related issue the github issue should go in this repo.

https://github.com/torch/nn/blob/getParamsByDevice/Module.lua

In this type() function won't recurse on table members that are (potentially nested) tables.  This means that type fails for any modules that have table output and gradInputs (of which there are a few, like FlattenTable, JoinTable, etc).  I fixed this bug in a previous pull request to the master nn branch.  For comparison:

https://github.com/torch/nn/blob/master/Module.lua

Are there any plans to merge the getParamsByDevice branch into master so that bug fixes can be incorporated?  Or are the two branches too divergent at this point?

**Comment by jonathantompson** [comment]
FYI: I put up a quick fix to my own fork:

https://github.com/jonathantompson/nn/commit/37b71e7a81d36aca9e3a03f227bec53dd7c4bd9e

Want me to post a PR in nn?

**Comment by soumith** [comment]
fixed it by rebasing the nn getParametersByDevice branch.

**Comment by jonathantompson** [comment]
Awesome. You're amazing!
