### ISSUE TITLE
DataParallel setup bug

### ISSUE THREAD

**Issue by qassemoquab** [facebook/fbcunn#27]
Hi,

I had some issues with nn.DataParallel :

1) I see that nn.Optim looks for the _mixGrads method in self.model
https://github.com/facebook/fbnn/blob/master/fbnn/Optim.lua line 152 :
if self.model._mixGrads then
self.model:_mixGrads()
end

2) _mixGrads doesn't exist in nn.Sequential, but exists in nn.DataParallel
https://github.com/torch/nn/blob/master/Sequential.lua
https://github.com/facebook/fbcunn/blob/master/luasrc/DataParallel.lua

3) example models are built like :
https://github.com/facebook/fbcunn/blob/master/examples/imagenet/models/overfeat_fbcunn.lua line 54 :
local model = nn.Sequential():add(features):add(classifier)
(where features is a nn.DataParallel)

=> Since model is a nn.Sequential, nn.Optim will not call the _mixGrads method (am I understanding it right ?)

I had an issue with a 4-GPU CIFAR-10 network that had a nn.DataParallel in a nn.Sequential, where I observed much slower convergence.
It converged much faster without the DataParallel. But I believe this is almost impossible to see on the ImageNet example because convergence takes forever anyway.

**Comment by soumith** [comment]
looks like you're onto something. looking into it. cc @ajtulloch @tudor

**Comment by qassemoquab** [comment]
I think _mixGrads should be inside nn.DataParallel:accGradParameters() instead of nn.Optim

**Comment by soumith** [comment]
have you already fixed it for yourself and tested it?

**Comment by qassemoquab** [comment]
Unfortunately not.
I just observed that very recently and went on with my experiments without parallelism.

**Comment by soumith** [comment]
I think the reason we did not observe this is because we were using the *Parallel modules always as the outer containers.

**Comment by soumith** [comment]
I have a fix in-flight, will push soon

**Comment by soumith** [comment]
@qassemoquab fixed this bug in https://github.com/facebook/fbcunn/commit/55beb7fa67b838a40e9d6cee8026e908d644665b

Please reinstall fbnn and fbcunn (just do git pull and luarocks make)
