### ISSUE TITLE
AbstractParallel has ModelParallel-specific behavior

### ISSUE THREAD

**Issue by qassemoquab** [facebook/fbcunn#28]
https://github.com/facebook/fbcunn/blob/master/luasrc/AbstractParallel.lua lines 235-256

AbstractParallel sums up the gradInputs, which is behavior that, I think, should be specific to ModelParallel.
DataParallel should concatenate the gradInputs instead (otherwise it's not possible to plug a DataParallel inside a network).

```lua
require 'fbcunn'
require 'cudnn'

basenet=nn.Sequential()
layer=cudnn.SpatialConvolution(3,16,5,5,1,1)
basenet:add(layer)
basenet:add(cudnn.ReLU())

model=nn.DataParallel(1)
model:add(basenet)
model:add(basenet:clone())
model:cuda()

inputTensor=torch.CudaTensor(32,3,10,10)
model:forward(inputTensor)

foo=model.output:clone()
model:backward(inputTensor, foo)
print(inputTensor:size())
print(model.gradInput:size())

```

Sizes should match but don't.

**Comment by qassemoquab** [comment]
I would put a call to a _mixGradInputs method in nn.AbstractParallel, that would be specific to Model/DataParallel (that's how I fixed it locally but my code isn't clean)

**Comment by soumith** [comment]
@jonathantompson also reported the same. cc: @ajtulloch @tudor

**Comment by soumith** [comment]
fix in-fight, will push soon.

**Comment by jonathantompson** [comment]
I'm re-writing DataParallel for my own codebase because I also need to be able to a) embed it in another module and b) support table inputs and outputs.

Would this be useful for anyone?  Or would too many versions of DataParallel just be confusing for the end user?

**Comment by soumith** [comment]
i've fixed the (a) already, will push tomorrow or so. (b) will be useful. As many versions of DataParallel as needed, looking forward to your version.

**Comment by soumith** [comment]
@qassemoquab fixed this bug in https://github.com/facebook/fbcunn/commit/55beb7fa67b838a40e9d6cee8026e908d644665b

Please reinstall fbnn and fbcunn (just do git pull and luarocks make)

**Comment by qassemoquab** [comment]
Thanks !
I have a small doubt though : I think it's not possible to do accUpdateGradParameters on DataParallel modules since it accumulates gradients directly on the weight tensors. (In that case, _mixGrads in AbstractParallel doesn't help ; one would need a _mixWeights instead.)

Looks very nice otherwise ! Thanks for the quick fixes !

**Comment by soumith** [comment]
you're right about the _mixWeights. Will fix that on monday. thanks for the review.
