### ISSUE TITLE
imagenet example: seg fault when test() is skipped

### ISSUE THREAD

**Issue by mmmikael** [facebook/fbcunn#3]
The second training epoch gives a segmentation fault if the test phase is skipped. This can be reproduced by simply commenting the ```test()``` call in ```examples/imagenet/main.lua```.

This seems related to the activation trimming at the end of ```train()```. 
If I do that on a cloned model, it works fine:
```lua
   -- save model
   model:float()
   local fmodel = model:clone() -- do clone on cpu
   fmodel:for_each(function(mod)
                     -- Trim activations so the checkpoint is not too huge
                     mod.output = mod.output.new()
                     mod.gradInput = mod.gradInput.new()
   end)
   torch.save(paths.concat(opt.save, 'model_' .. epoch .. '.t7'), fmodel)
   torch.save(paths.concat(opt.save, 'optimState_' .. epoch .. '.t7'), optimState)
```

**Comment by soumith** [comment]
the code that you pasted here is not the one in trunk. i patched it already according to your comments:
https://github.com/facebook/fbcunn/commit/de9fa6db3e35c8630c68560a2a024ff7ca632b2c
https://github.com/facebook/fbcunn/commit/c479f567275ed0f2d45d89edf7e563661b7228ad

I've tested it out with the test() commented, works good now.
