### ISSUE TITLE
Resulting Model display

### ISSUE THREAD

**Issue by nakohli** [facebook/fbcunn#30]
Hi,
I have been able to install the library and run the alexnet example code on my machine.  I have the resulting torch files for the models in each epoch and the optimstate file. I was wondering if there is a way to visualize the model learnt ( eg. showing the output kernels as an image ). I am not sure if the feature already exists so if you could point me there that would work too !

Thanks a lot !

**Comment by ajtulloch** [comment]
@nakohli, check out In[4] in http://nbviewer.ipython.org/github/facebook/iTorch/blob/master/iTorch_Demo.ipynb.

**Comment by ajtulloch** [comment]
http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb has some other things you could try as well.

**Comment by nakohli** [comment]
@ajtulloch Thanks for replying so quickly and pointing me to the itorch resource. I have been able to load the module and am able to see the attributes inside model. However, I was unable to identify how to reach to the weight attributes. My initial guess was to reach the individual modules like cudnn.SpatialConvolution of the model and then hopefully do the same thing done in the link you have provided.  I have used the default alexnet model but if I do something like model.listModules(), it just gives me error written below. Could you give me some hints to what could be the problem or if I am going the wrong way to visualize the weights. Thanks !
```
In [11]: model.listModules()
/home/anon/torch/install/share/lua/5.1/nn/Module.lua:374: attempt to index local 'self' (a nil value)
stack traceback:
	/home/anon/torch/install/share/lua/5.1/nn/Module.lua:374: in function 'f'
	[string "local f = function() return model.listModules..."]:2: in main chunk
	[C]: in function 'xpcall'
	/home/anon/torch/install/share/lua/5.1/itorch/main.lua:194: in function </home/anon/torch/install/share/lua/5.1/itorch/main.lua:160>
	/home/anon/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	/home/anon/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	/home/anon/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	/home/anon/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	/home/anon/torch/install/share/lua/5.1/itorch/main.lua:374: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
```

**Comment by ajtulloch** [comment]
Try `model:listModules()`

**Comment by nakohli** [comment]
@ajtulloch 

Okay thanks a lot for your response, 

I hate to ask but I have tried a lot to get this right but still can't. I want access to a particular layer to see its weights. Writing model:listModules() I see that Layer 28 is the last layer with convolution before the classifier layer and also has the weight attributes. I have tried using the get method thinking that it would give me the access to this layer but that does not work.

Looking at the readme provided, it says that we can use the `forward` method to evaluate the prediction of a new testing image.  But I am unable to find this method to see how you can access a particular module one by one. Could you help me figure out how to get access to a particular module such as module 28 in the net ?

Thanks a lot for your support !

```
 28 : 
    cudnn.SpatialConvolution
    {
      bias : CudaTensor - size: 128
      kW : 3
      gradInput : CudaTensor - size: 128x192x13x13
      groups : 1
      gradWeight : CudaTensor - size: 128x192x3x3
      output : CudaTensor - size: 128x128x13x13
      scaleT : FloatTensor - size: 1
      weight_offset : 221184
      _type : torch.CudaTensor
      dH : 1
      padding : 0
      padW : 1
      nInputPlane : 192
      gradBias : CudaTensor - size: 128
      dW : 1
      extraBuffer : CudaTensor - size: 6912
      input_offset : 32448
      nOutputPlane : 128
      weight : CudaTensor - size: 128x192x3x3
      train : true
      output_offset : 21632
      iSize : LongStorage - size: 4
      bias_offset : 128
      kH : 3
      padH : 1
    }
```

**Comment by ajtulloch** [comment]
@nakohli hop in https://gitter.im/torch/torch7 and it will be easier to debug.

**Comment by LijieTu** [comment]
@nakohli 
Hi, I came across the same problem. Did you find a convenient method to vis the feature maps after the convolution and also the filter itself (especially the higher layers)? Thanks!
