### ISSUE TITLE
Crash when trying to run imagenet example with -backend fbcunn

### ISSUE THREAD

**Issue by rbjarnason** [facebook/fbcunn#35]
```
/home/ubuntu/torch-distro/install/bin/luajit: ...ubuntu/torch-distro/install/share/lua/5.1/trepl/init.lua:319: ...ubuntu/torch-distro/install/share/lua/5.1/trepl/init.lua:319: module 'fb.util.dbg' not found:No LuaRocks module found for fb.util.dbg
	no field package.preload['fb.util.dbg']
...
stack traceback:
	[C]: in function 'error'
	...ubuntu/torch-distro/install/share/lua/5.1/trepl/init.lua:319: in function 'require'
	...buntu/fbcunn/examples/imagenet/models/alexnet_fbcunn.lua:1: in main chunk
	[C]: in function 'dofile'
	/home/ubuntu/fbcunn/examples/imagenet/model.lua:23: in main chunk
```
Any ideas?

**Comment by soumith** [comment]
i dont know if you installed fbcunn properly. You seem to be missing fblualib.
Please follow instructions from here:
https://github.com/facebook/fbcunn/blob/master/INSTALL.md

**Comment by rbjarnason** [comment]
I did a re-install with curl -sk https://raw.githubusercontent.com/soumith/fblualib/master/install_all.sh | bash

And the install did seem to work but now another crash:
```
...
nClasses: 	2	
nTest: 	101	
ERROR: something wrong with flag 'mlock_chunk_size' in file 'MemoryMapping.cpp'.  One possibility: file 'MemoryMapping.cpp' is being linked both statically and dynamically into this executable
```

I'm testing on an Amazon G2, at first I did follow the INSTALL.md but there were some issues, so I used this public image: ami-a0e4b1c8 that has everything setup, except fbnn and nn.

The imagenet example does seems to be working for training and validation when using cudnn and cunn backends with cudnn considerably faster than cunn as expected.

**Comment by soumith** [comment]
fbcunn backend for convolution layers might not work with Amazon G2 instances, because the instances have CUDA 3.0 capable cards, where as fbcunn backend requires CUDA 3.5 capable cards.

The only parts of fbcunn that are good to use in the G2 instances are the lua containers like nn.DataParallel and nn.ModelParallel.

**Comment by AndrewLavin** [comment]
The right thing to do is check the compute capability at runtime using cudaGetDeviceProperties and generate an error message if the minimum capability is not met. That way there is no confusion as to the cause of the error.

**Comment by rbjarnason** [comment]
Thanks for the info guys.
