### ISSUE TITLE
I don't think overfeat implementation is right, not that simple

### ISSUE THREAD

**Issue by northeastsquare** [facebook/fbcunn#36]
Acording to the paper :OverFeat:Integrated Recognition, Localization and Detection using Convolutional Networks
3.3 Multi-Scale Classification

**Comment by soumith** [comment]
I implemented overfeat-fast network according to the paper more or less. Let me know where you think its not right.

**Comment by northeastsquare** [comment]
Thank you for reply!
1. I have not found the following procedure in your implementation:
(a) For a single image, at a given scale, we start with the unpooled layer 5 feature maps.
(b) Each of unpooled maps undergoes a 3x3 max pooling operation (non-overlapping regions),
repeated 3x3 times for (∆ x , ∆ y ) pixel offsets of {0, 1, 2}.
(c) This produces a set of pooled feature maps, replicated (3x3) times for different (∆ x , ∆ y ) com-
binations.
(d) The classifier (layers 6,7,8) has a fixed input size of 5x5 and produces a C-dimensional output
vector for each location within the pooled maps. The classifier is applied in sliding-window
fashion to the pooled maps, yielding C-dimensional output maps (for a given (∆ x , ∆ y ) combi-
nation).
(e) The output maps for different (∆ x , ∆ y ) combinations are reshaped into a single 3D output map
(two spatial dimensions x C classes).
2. I have not find multi-scale implementation.
3.overfeat-fast also has drop-out 
"DropOut [11] with a rate of 0.5 is employed on the fully connected layers (6th and 7th) in the classifier." 
4.image flip: P6"The procedure above is repeated for the horizontally flipped version of each image."
5.P12 "we perform negative training on the fly, by selecting a few interesting negative examples per image such as random ones or most offending ones."
Thanks.

**Comment by northeastsquare** [comment]
also, "Note that the last layers of our architecture are fully connected linear layers. At test time, these
layers are effectively replaced by convolution operations with kernels of 1x1 spatial extent."

**Comment by soumith** [comment]
Ive implemented the overfeat-fast classification network, only for classification. You are talking about detection.
