### ISSUE TITLE
Installation on Ubuntu Server 14.04 LTS

### ISSUE THREAD

**Issue by amiralush** [facebook/fbcunn#4]
Is it compatible with Ubuntu Server 14.04 LTS ?
If so, which gcc version should I use ?
I'm asking this because it doesn't go as smoothly as I expected.

Thanks!

**Comment by soumith** [comment]
Yes, I've tested the install process multiple times on a clean and fresh Ubuntu 14.04 Amazon EC2 GPU instance.

Could you tell me where you might be erroring out? 
Which stage in the https://github.com/facebook/fbcunn/blob/master/INSTALL.md process did you get to, and if you can paste any logs, that would be helpful.

**Comment by amiralush** [comment]
Install Torch in a local folder -- > bash install.sh
I'm getting the following error:

/tmp/fblualib-build.keIFqJ/fblualib/fblualib/python/Lib.cpp: In function ‘fblualib::python::PyObjectHandle {anonymous}::{anonymous}::defaultFromList(lua_State*)’:
/tmp/fblualib-build.keIFqJ/fblualib/fblualib/python/Lib.cpp:127:45: error: ‘PyString_FromString’ was not declared in this scope
   PyObjectHandle all(PyString_FromString("*"));

My python version is 2.7.8

**Comment by soumith** [comment]
I see that you are at this stage: https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-folly-fbthrift-thpp-and-fblualib

Even though your python version is 2.7.8, there seems to be a system python that is 3+ that is being built with fbpython (fbpython is incompatible with python 3.0+). Strangely I did not encounter this error in my builds.

I just disabled the installation of fbpython during the installation process, as fbcunn does not depend on fbpython at all.

So starting from that section, try the commands again, this time it wont build fbpython.

**Comment by amiralush** [comment]
Thanks, I'm not getting this error anymore.

But, after running luarocks make rocks/fbcunn-scm-1.rockspec
I'm getting the following:

[  2%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/cuda/fft/./fbcunnlayers_cuda_generated_CuFFTConvolution_UpdateGradInput.cu.o
In file included from /usr/local/cuda/include/cuda_runtime.h:59:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:82:2: error: #error -- unsupported GNU version! gcc 4.9 and up are not supported!
 #error -- unsupported GNU version! gcc 4.9 and up are not supported!
  ^
CMake Error at fbcunnlayers_cuda_generated_CuFFTConvolution_UpdateGradInput.cu.o.cmake:206 (message):
  Error generating
  /home/amiralush/nn/fbcunn/build/CMakeFiles/fbcunnlayers_cuda.dir/src/cuda/fft/./fbcunnlayers_cuda_generated_CuFFTConvolution_UpdateGradInput.cu.o


CMakeFiles/fbcunnlayers_cuda.dir/build.make:167: recipe for target 'CMakeFiles/fbcunnlayers_cuda.dir/src/cuda/fft/./fbcunnlayers_cuda_generated_CuFFTConvolution_UpdateGradInput.cu.o' failed
make[2]: *** [CMakeFiles/fbcunnlayers_cuda.dir/src/cuda/fft/./fbcunnlayers_cuda_generated_CuFFTConvolution_UpdateGradInput.cu.o] Error 1
CMakeFiles/Makefile2:130: recipe for target 'CMakeFiles/fbcunnlayers_cuda.dir/all' failed
make[1]: *** [CMakeFiles/fbcunnlayers_cuda.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

Which brings me back to the gcc version issue.  Should I use 4.8 or 4.7 ?

Thanks again

**Comment by soumith** [comment]
i've used the version that ships with Ubuntu 14, which is 4.8.2

**Comment by amiralush** [comment]
I think that in one the scripts there is an update of g++ which upgrades the default gcc to 4.9

**Comment by amiralush** [comment]
@soumith Thanks for your help. 
Everything now works. I had to clean-up everything and start from step 1 using gcc-4.8

**Comment by soumith** [comment]
thanks for the feedback. i'll add graphicsmagick to the install scripts now.
