### ISSUE TITLE
Seg fault using TemporalConvolutionFB

### ISSUE THREAD

**Issue by ET-Chan** [facebook/fbcunn#45]
It seems it is caused by a recent update of cutorch 3 days ago. Specifically,
```
int curDev;
THCudaCheck(cudaGetDevice(&curDev));
if(self->device != THC_DEVICE_NONE) {
if (THCState_getDeviceMode(state) == THCStateDeviceModeAuto) {
   THCudaCheck(cudaSetDevice(self->device));
}
else if(self->device != curDev) {
   THError("THCudaStorage_resize: device mismatch: tensorDev=%d, curDev=%d", self->device + 1, curDev + 1);
}
```
line 29-38 from function THCudaStorage_resize()  in THC/THCStorage.cu has been changed, using THCstate now.

At the same time, resizing is sometimes invoked by the module, namely
```
THCudaTensor_resize3d(NULL, outputTH,
                            nBatchFrame,
                            nOutputTHFrame,
                            outputTHFrameSize);
```
line 96 from cuda/TemporalConvolutionFBHost.cpp. NULL is passed through as THCState and leads to access violation. Not sure if it affects other modules.

**Comment by soumith** [comment]
reinstall both fbnn and fbcunn (I just updated them now), should be fixed after that.

https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-fbcunn
