### ISSUE TITLE
system crash using overfeat model,alexnet ok

### ISSUE THREAD

**Issue by northeastsquare** [facebook/fbcunn#47]
I use titan x, tried alexnet either backend cudnn or fbcunn ,everything well.
But use overfeat either backend cudnn or fbcunn ,system crash after screen print 'epoch 1',
I also tried imagenet-multiGPU.torch, all the same.
Thank you for your time!

**Comment by northeastsquare** [comment]
system crash, I mean computer suddenly restart.

**Comment by andravin** [comment]
This sounds like a hardware problem, there is not enough power going to the GPU. You will only notice the problem when computational efficiency is high enough to increase the power consumption above a certain threshold.

**Comment by northeastsquare** [comment]
Thank you, andravin, Yes, the GPU's problem. Reinstall NVIDIA-Linux-x86_64-346.59.run, and cuda , solve it.
