### ISSUE TITLE
nn.Module._gather doesn't seem to be defined anywhere

### ISSUE THREAD

**Issue by pyadolla** [facebook/fbcunn#49]
I get an error when running fb_test.lua,

>>>>>>>>> TestTorch	
>>> TestTorch:test_Module_getParametersByDevice	
...greg/common/torch-openblas/share/lua/5.1/fbcunn/init.lua:68: attempt to call field '_gather' (a nil value)	
Failed	

I don't see _gather defined anywhere in 'nn' or 'fbcunn'.

**Comment by soumith** [comment]
_gather is defined in getParamsByDevice branch of nn. 

According to the installation instructions of fbcunn:
https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-fbcunn

You install that branch, using the command:

git clone https://github.com/torch/nn && cd nn && git checkout getParamsByDevice && luarocks make rocks/nn-scm-1.rockspec

**Comment by pyadolla** [comment]
Thanks. After switching to the getParamsByDevice branch of nn I get a problem when testing cunn - looks like new fields where introduced in nn.PReLU:__init.

th -lcunn -e "nn.testcuda()"

PReLU_backward
 Function call failed 
...on-greg/common/torch-openblas/share/lua/5.1/nn/PReLU.lua:22: bad argument #1 (field gradWeightBuf does not exist)
stack traceback:
	[C]: in function 'PReLU_accGradParameters'
	...on-greg/common/torch-openblas/share/lua/5.1/nn/PReLU.lua:22: in function 'accGradParameters'

**Comment by soumith** [comment]
that was my bad. I rebased the getParamsByDevice branch now. If you rerun the command

git clone https://github.com/torch/nn && cd nn && git checkout getParamsByDevice && luarocks make rocks/nn-scm-1.rockspec

you should be good to go.

**Comment by rudrapoudel** [comment]
Hi Soumith, 

Got new error,

```
> th fb_test.lua
>>>>>>>>> TestTorch	
>>> TestTorch:test_Module_getParametersByDevice	
>>> TestTorch:test_Optim	
...p14/libraries/torch/install/share/lua/5.1/trepl/init.lua:363: module 'fboptim' not found:No LuaRocks module found for fboptim
	no field package.preload['fboptim']
	no file '/home/rp14/.luarocks/share/lua/5.1/fboptim.lua'
	no file '/home/rp14/.luarocks/share/lua/5.1/fboptim/init.lua'
	no file '/home/rp14/libraries/torch/install/share/lua/5.1/fboptim.lua'
	no file '/home/rp14/libraries/torch/install/share/lua/5.1/fboptim/init.lua'
	no file './fboptim.lua'
	no file '/home/rp14/libraries/torch/install/share/luajit-2.1.0-alpha/fboptim.lua'
	no file '/usr/local/share/lua/5.1/fboptim.lua'
	no file '/usr/local/share/lua/5.1/fboptim/init.lua'
	no file '/home/rp14/.luarocks/lib/lua/5.1/fboptim.so'
	no file '/home/rp14/libraries/torch/install/lib/lua/5.1/fboptim.so'
	no file './fboptim.so'
	no file '/usr/local/lib/lua/5.1/fboptim.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'	
Failed	
>>> TestTorch:test_TemporalMaxPooling	
>>> TestTorch:test_TemporalMaxPoolingBatch	
```
