### ISSUE TITLE
fbcunn installation problem

### ISSUE THREAD

**Issue by mrastegari** [facebook/fbcunn#50]
I am trying to install fbcunn and I get this error: 
![screen shot 2015-05-13 at 5 37 41 pm](https://cloud.githubusercontent.com/assets/1390657/7625841/0bcea278-f9b2-11e4-9673-2f71d6312e90.png)

Any idea why?

**Comment by soumith** [comment]
Did you follow the instructions in https://github.com/facebook/fbcunn/blob/master/INSTALL.md

You seem to be missing folly, which is the 4th step: https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-folly-fbthrift-thpp-and-fblualib

**Comment by mrastegari** [comment]
Folly installs without any problem but it seems that thrift has some problem during the config. It can not link against folly
![screen shot 2015-05-14 at 12 05 53 am](https://cloud.githubusercontent.com/assets/1390657/7627697/c4fa1d38-f9ce-11e4-8710-44ef040413e0.png)

**Comment by rudrapoudel** [comment]
Looks libfolly.so.xx isn't in your path i.e. if you are following the standard installation script then add following line to ~/.bash_profile or/and ~/.bashrc
```
export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
```
Then,
```
> source ~/.profile
```
Now, run the installation script again.

**Comment by mrastegari** [comment]
I have the libfolly.so.xx files in  /usr/local/lib 
![screen shot 2015-05-14 at 11 24 13 am](https://cloud.githubusercontent.com/assets/1390657/7638954/6f042752-fa2d-11e4-900d-e6feaf32be7f.png)
and also I have the path in the LD_LIBRARY_PATH
![screen shot 2015-05-14 at 11 35 02 am](https://cloud.githubusercontent.com/assets/1390657/7638965/87bb8a1a-fa2d-11e4-9f70-789617552a10.png)
But still I have the same error

**Comment by ndronen** [comment]
I found that simply running `sudo ldconfig` was sufficient to work around this.  If it works, you should be able to confirm by running `sudo ldconfig -v | grep folly'.  Notice here that I don't have /usr/local/lib in my LD_LIBRARY_PATH.

```bash
$ echo $LD_LIBRARY_PATH
/export/home/ndronen/proj/torch/install/lib:
$ sudo ldconfig -v | grep folly
        libfolly.so.38 -> libfolly.so.38.0.0
        libfollybenchmark.so.38 -> libfollybenchmark.so.38.0.0
```

**Comment by ndronen** [comment]
If running `sudo ldconfig` works for @mrastegari, perhaps the command should be added to the end of the block where folly gets installed.  Here's the version of the machine where ldconfig worked for me:

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

**Comment by mrastegari** [comment]
What was the version of gcc? mine is 4.9.2. 'sudo ldconfig -v | grep folly' could not solve my problem. Again I am getting the same error I have exactly the same os as yours:  
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by ndronen** [comment]
$ gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

**Comment by soumith** [comment]
@ndronen thanks, I added the "sudo ldconfig" to the script and that does indeed help.

@mrastegari 

sorry about this. I just fixed the fblualib install script so that this error does not happen now.
I made sure tagged versions of folly and fbthrift are installed, rather than trunk. I tested the install process on a fresh ubuntu 14.04 machine.

You'll have to redo the install process starting from this step:
https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-folly-fbthrift-thpp-and-fblualib

Let me know if it works this time for you, if not please reopen the issue, I'll try to help you as much as I can.
