### ISSUE TITLE
Using nn.Sequential with nn.HSM throws error

### ISSUE THREAD

**Issue by aliaslam1992** [facebook/fbcunn#52]
Is it meant to be used with nn.Sequential? It calls HSM.updateOutput(input, target) without a target argument at https://github.com/torch/nn/blob/master/Sequential.lua#L29.

I receive this error with CUDA (fbcunn):
HSM.lua:197: attempt to index local 'target' (a nil value)
It fails here without CUDA (fbnn):
https://github.com/facebook/fbnn/blob/master/fbnn/HSM.lua#L182

**Comment by soumith** [comment]
HSM is a criterion. it takes an input, target like the Criterion interface, and derives from nn.Criterion. So it cant be used as a module.

**Comment by aliaslam1992** [comment]
Tried to run test_HSM.lua, still got an (unrelated) error:
/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/torch/install/share/lua/5.1/fbnn/HSM.lua:187: attempt to call field 'HSM_updateOutputWithTarget' (a nil value)
stack traceback:
	/home/ubuntu/torch/install/share/lua/5.1/fbnn/HSM.lua:187: in function 'updateOutput'

**Comment by soumith** [comment]
the test is for the CPU version of HSM, which requires MKL. So I disabled the compilation of the CPU parts in the open source branch. If you run the test after converting the nn.HSM modules to CUDA, it'll work.
