### ISSUE TITLE
"nn.Optim has been already assigned a factory"

### ISSUE THREAD

**Issue by pratikac** [facebook/fbcunn#53]
I get the following error message when I try to use fbcunn (cudnn works fine).
```
/usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:363: /usr/local/share/lua/5.1/trepl/init.lua:363: /usr/local/share/lua/5.1/torch/init.lua:62: nn.Optim has been already assigned a factory
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/trepl/init.lua:363: in function 'require'
        ...de/torch/gittorch/imagenet-gpu/models/alexnet_fbcunn.lua:1: in main chunk
```

**Comment by soumith** [comment]
Comment out the lines that load fbcunn_files. I'm assuming you're using https://github.com/soumith/imagenet-multiGPU.torch which was explicitly isolating all dependencies on fbcunn because fbcunn was difficult for many people to install.

**Comment by pedropgusmao** [comment]
I am getting the same problem but in my case I am launching in parallel the same script using cudnn in another GPU. I am just changing the cache folder and backend.  

Should I proceed in the same way and comment that line or will it interfere the already running cudnn training?
  
Thanks
