### ISSUE TITLE
THCState_getCurrentStream is undefined

### ISSUE THREAD

**Issue by Hokie23** [facebook/fbcunn#56]
Getting a weird undefined error, I've pasted the output. I am running ubuntu 14.04 with cuda 6.5 and nvidia 340.29.

cyclops@xaviers:~/torch/nn$ cd fbcunn && luarocks make rocks/fbcunn-scm-1.rockspec
   git submodule init
   git submodule update
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PRE                   FIX_PATH="/home/cyclops/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/ukrothapall                   i/torch/install/lib/luarocks/rocks/fbcunn/scm-1"

Submodule 'cuda' (https://github.com/facebook/fbcuda.git) registered for path 'cuda'
Cloning into 'cuda'...
remote: Counting objects: 126, done.
remote: Total 126 (delta 0), reused 0 (delta 0), pack-reused 126
Receiving objects: 100% (126/126), 118.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (53/53), done.
Checking connectivity... done.
Submodule path 'cuda': checked out '26f01ee8f8a3035cd58adb5ccf02245e58c06c04'
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/cyclops/torch/install
-- Found Folly: /usr/local/include
-- Found CUDA: /usr/local/cuda-6.5 (found suitable version "6.5", minimum required is "6.5")                   
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cyclops/torch/nn/fbcunn/build
cd build && make install
[  2%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/util/./fbcunnlayer                   s_cuda_generated_Transform.cu.o
[  4%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cud                   a_generated_CrossMapNormalization.cu.o
[  6%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cud                   a_generated_FeatureLPPooling.cu.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

[  9%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cud                   a_generated_HalfPrecKernels.cu.o
[ 11%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cud                   a_generated_HSM.cu.o
[ 13%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cud                   a_generated_LookupTableGPU.cu.o
[ 15%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cud                   a_generated_OneBitQuantization.cu.o
[ 18%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cud                   a_generated_SparseNLLCriterion.cu.o
[ 20%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cud                   a_generated_TemporalKMaxPooling.cu.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

[ 22%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cud                   a_generated_ConvolutionBias.cu.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

/home/cyclops/torch/nn/fbcunn/src/ConvolutionBias.cu(162): error: identifier "THCState_                   getCurrentStream" is undefined

/home/cyclops/torch/nn/fbcunn/src/ConvolutionBias.cu(187): error: identifier "THCState_                   getCurrentStream" is undefined

/home/cyclops/torch/nn/fbcunn/src/ConvolutionBias.cu(222): error: identifier "THCState_                   getCurrentStream" is undefined

/home/cyclops/torch/nn/fbcunn/src/ConvolutionBias.cu(252): error: identifier "THCState_                   getCurrentStream" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_0000e717_00000000-6_ConvolutionBias.cpp                   1.ii".
CMake Error at fbcunnlayers_cuda_generated_ConvolutionBias.cu.o.cmake:264 (message):
  Error generating file
  /home/cyclops/torch/nn/fbcunn/build/CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlaye                   rs_cuda_generated_ConvolutionBias.cu.o

make[2]: *** [CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_Convolution                   Bias.cu.o] Error 1
make[1]: *** [CMakeFiles/fbcunnlayers_cuda.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed installing.
cyclops@xaviers:~/torch/nn/fbcunn$ cd ..
cyclops@xaviers:~/torch/nn$ cd fbcunn && luarocks make rocks/fbcunn-scm-1.rockspec
   git submodule init
   git submodule update
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/cyclops/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/cyclops/torch/install/lib/luarocks/rocks/fbcunn/scm-1"

-- Found Torch7 in /home/cyclops/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cyclops/torch/nn/fbcunn/build
cd build && make install
[  2%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_FeatureLPPooling.cu.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

[  4%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_TemporalKMaxPooling.cu.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

[  6%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_ConvolutionBias.cu.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

/home/cyclops/torch/nn/fbcunn/src/ConvolutionBias.cu(162): error: identifier "THCState_getCurrentStream" is undefined

/home/cyclops/torch/nn/fbcunn/src/ConvolutionBias.cu(187): error: identifier "THCState_getCurrentStream" is undefined

/home/cyclops/torch/nn/fbcunn/src/ConvolutionBias.cu(222): error: identifier "THCState_getCurrentStream" is undefined

/home/cyclops/torch/nn/fbcunn/src/ConvolutionBias.cu(252): error: identifier "THCState_getCurrentStream" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_0000ea99_00000000-6_ConvolutionBias.cpp1.ii".
CMake Error at fbcunnlayers_cuda_generated_ConvolutionBias.cu.o.cmake:264 (message):
  Error generating file
  /home/cyclops/torch/nn/fbcunn/build/CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_ConvolutionBias.cu.o

make[2]: *** [CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_ConvolutionBias.cu.o] Error 1
make[1]: *** [CMakeFiles/fbcunnlayers_cuda.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed installing.

**Comment by Hokie23** [comment]
added the paths to bashrc, closing the issue.

**Comment by jarmstrong2** [comment]
I'm getting the same error, what was the path you added

**Comment by Hokie23** [comment]
I added paths to the headers and libraries. Do you still have this problem?

**Comment by pedropgusmao** [comment]
Hello, I am getting the same error.
`git pull` gives me "Already up-to-date"....

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h


/home/ubuntu/repositories/fbcunn/src/ConvolutionBias.cu(162): error: identifier "THCState_getCurrentStream" is undefined

/home/ubuntu/repositories/fbcunn/src/ConvolutionBias.cu(187): error: identifier "THCState_getCurrentStream" is undefined

/home/ubuntu/repositories/fbcunn/src/ConvolutionBias.cu(222): error: identifier "THCState_getCurrentStream" is undefined

/home/ubuntu/repositories/fbcunn/src/ConvolutionBias.cu(252): error: identifier "THCState_getCurrentStream" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_00009ad6_00000000-7_ConvolutionBias.cpp1.ii".
CMake Error at fbcunnlayers_cuda_generated_ConvolutionBias.cu.o.cmake:264 (message):
  Error generating file
  /home/ubuntu/repositories/fbcunn/build/CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_ConvolutionBias.cu.o


make[2]: *** [CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_ConvolutionBias.cu.o] Error 1
make[1]: *** [CMakeFiles/fbcunnlayers_cuda.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed installing.

**Comment by Hokie23** [comment]
I added paths to the include and lib directories in usr/local/.
