### ISSUE TITLE
[EC2] cuda run time error specifically with fbcunn

### ISSUE THREAD

**Issue by deeperlearning** [facebook/fbcunn#57]
I'm running fbcunn on a gpu instance on AWS. cutorch and basic neural networks in Torch with :cuda() work fine for me. When I try and use LookupTableGPU, I get:

/home/ubuntu/torch/install/bin/luajit: ...e/ubuntu/torch/install/share/lua/5.1/nn/BCECriterion.lua:21: /home/ubuntu/torch/extra/cutorch/lib/THC/THCTensorMath.cu(33) : cuda runtime error : invalid device function at /home/ubuntu/torch/extra/cutorch/lib/THC/THCGeneral.c:263

**Comment by soumith** [comment]
Please read this issue: https://github.com/facebook/fbcunn/issues/23
