### ISSUE TITLE
Missing fbnn & fbtorch

### ISSUE THREAD

**Issue by amiralush** [facebook/fbcunn#6]
It seems like fbnn & fbtorch are missing.
I was able to install fbnn, but wasn't successful installing fbtorch (https://github.com/facebook/fbtorch)
Can you please advise?

**Comment by soumith** [comment]
why would you require fbtorch? i've removed all dependency on fbtorch from this module. let me know if there's some artifacts that are left.

fbnn is only required to run certain unit tests, in general fbnn is not needed at this point to use fbcunn (last I checked)

**Comment by amiralush** [comment]
The error I'm getting is while running the imagenet example:

==> Converting model to CUDA
/home/amiralush/torch-distro/install/bin/luajit: ...ralush/torch-distro/install/share/lua/5.1/trepl/init.lua:319: ...ralush/torch-distro/install/share/lua/5.1/trepl/init.lua:319: module 'fbtorch' not found:No LuaRocks module found for fbtorch
        no field package.preload['fbtorch']
        no file '/home/amiralush/.luarocks/share/lua/5.1/fbtorch.lua'
        no file '/home/amiralush/.luarocks/share/lua/5.1/fbtorch/init.lua'
        no file '/home/amiralush/torch-distro/install/share/lua/5.1/fbtorch.lua'
        no file '/home/amiralush/torch-distro/install/share/lua/5.1/fbtorch/init.lua'
        no file './fbtorch.lua'
        no file '/home/amiralush/torch-distro/install/share/luajit-2.1.0-alpha/fbtorch.lua'
        no file '/usr/local/share/lua/5.1/fbtorch.lua'
        no file '/usr/local/share/lua/5.1/fbtorch/init.lua'
        no file '/home/amiralush/.luarocks/lib/lua/5.1/fbtorch.so'
        no file '/home/amiralush/torch-distro/install/lib/lua/5.1/fbtorch.so'
        no file './fbtorch.so'
        no file '/usr/local/lib/lua/5.1/fbtorch.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        ...ralush/torch-distro/install/share/lua/5.1/trepl/init.lua:319: in function 'require'
        /home/amiralush/nn/fbcunn/examples/imagenet/train.lua:10: in main chunk
        [C]: in function 'dofile'
        main.lua:30: in main chunk
        [C]: in function 'dofile'
        ...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00406170

Besides that, you have several tests in this repository the require fbtorch.

**Comment by soumith** [comment]
sorry you have been having these issues. i have fixed this in fbnn (weird i do not see this error).
Yes the imagenet example requires fbnn (but not fbtorch). 
Reinstall fbnn, and you will be good to go:
```bash
git clone https://github.com/facebook/fbnn.git && cd fbnn
luarocks make rocks/fbnn-scm-1.rockspec
```

**Comment by soumith** [comment]
hopefully this is the last error you have. i've tested the install on two systems, but looks like there's some things that might have already been installed on those machines. thanks again for reporting the issues.

**Comment by amiralush** [comment]
Great it works now!
Thanks so much for your super-fast responses and off course for your code.

**Comment by patrickhop** [comment]
had same issue. can confirm this works.

thanks @soumith

**Comment by omkarparkhi** [comment]
@soumith , can you please add fbnn installation to the installation guide please?
