### ISSUE TITLE
THCState_getCurrentStream is undefined

### ISSUE THREAD

**Issue by jarmstrong2** [facebook/fbcunn#60]
/home/ubuntu/torch/fbtorch/fbnn/fbcunn/src/ConvolutionBias.cu(162): error: identifier "THCState_getCurrentStream" is undefined

/home/ubuntu/torch/fbtorch/fbnn/fbcunn/src/ConvolutionBias.cu(187): error: identifier "THCState_getCurrentStream" is undefined

/home/ubuntu/torch/fbtorch/fbnn/fbcunn/src/ConvolutionBias.cu(222): error: identifier "THCState_getCurrentStream" is undefined

/home/ubuntu/torch/fbtorch/fbnn/fbcunn/src/ConvolutionBias.cu(252): error: identifier "THCState_getCurrentStream" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_00007786_00000000-7_ConvolutionBias.cpp1.ii".
CMake Error at fbcunnlayers_cuda_generated_ConvolutionBias.cu.o.cmake:264 (message):
  Error generating file
  /home/ubuntu/torch/fbtorch/fbnn/fbcunn/build/CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_ConvolutionBias.cu.o

make[2]: *** [CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_ConvolutionBias.cu.o] Error 1
make[1]: *** [CMakeFiles/fbcunnlayers_cuda.dir/all] Error 2
make: *** [all] Error 2

someone had the same issue, resolved it by adding to bashrc... but did not say what they added... any help would be appreciated

**Comment by soumith** [comment]
hey @jarmstrong2, those functions are defined in the latest cutorch/cunn. I wonder if you have an old installation of torch (somewhere on your machine) from which bad .h files are being picked up...

**Comment by jarmstrong2** [comment]
hey @soumith i'm using a prebuilt aws instance with torch pre installed.... I will attempt to reinstall fresh and see what happens

**Comment by soumith** [comment]
oh ok, that is probably why. that AMI is a little old. Reinstall torch with instructions from here: torch.ch/docs/getting-started.html#_

I am creating a new AMI , but wont be ready till this weekend.
