### ISSUE TITLE
Problem at "Install Folly, fbthrift, thpp and fblualib"

### ISSUE THREAD

**Issue by mszlazak** [facebook/fbcunn#61]
I had the latest cuda installed:
cuda-repo-ubuntu1404-7-0-local_7.0-28_amd64.deb
before going through these instruction. 

The link libfolly.so.43 wants something that isn't there.
Do i need to uninstall the 7.0 driver and install 6.5?

Making all in thrift
make[3]: Entering directory `/tmp/fblualib-build.US7QU3/fbthrift/thrift/lib/thrift'
../../compiler/thrift1 --gen cpp:templates,cob_style -r reflection.thrift
../../compiler/thrift1: error while loading shared libraries: libfolly.so.43: cannot open shared object file: No such file or directory
make[3]: *** [gen-cpp/reflection_constants.cpp] Error 127
make[3]: Leaving directory `/tmp/fblualib-build.US7QU3/fbthrift/thrift/lib/thrift'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/fblualib-build.US7QU3/fbthrift/thrift/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/fblualib-build.US7QU3/fbthrift/thrift'
make: *** [all] Error 2

**Comment by achansavang** [comment]
Had this issue too. I solved it by adding  /usr/local/lib to LD_LIBRARY_PATH:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

**Comment by mszlazak** [comment]
Thank you very much! That solved the first issue I had. There was and still is a second issue that occurs when installing fbcunn at the last step:

cd fbcunn && luarocks make rocks/fbcunn-scm-1.rockspec

Here is the end of the terminals output. Lot's of those CMake warnings about removing non-existent dependency files before what I have in the snippet below ... if that matters. Have any ideas?

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h


CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h


CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

[ 43%] Building NVCC (Device) object CMakeFiles/fbcunnlayers_cuda.dir/src/./fbcunnlayers_cuda_generated_MM.cu.o
Scanning dependencies of target fbcunnlayers_cuda
[ 45%] Building CXX object CMakeFiles/fbcunnlayers_cuda.dir/src/fft/CuFFTConvolution.cpp.o
In file included from /home/mark/nn/fbtorch/fbnn/fbcunn/src/fft/CuFFTConvolution.cpp:14:0:
/home/mark/nn/fbtorch/fbnn/fbcunn/src/fft/Utils.h:5:25: fatal error: thpp/Tensor.h: No such file or directory
 #include "thpp/Tensor.h"
                         ^
compilation terminated.
make[2]: *** [CMakeFiles/fbcunnlayers_cuda.dir/src/fft/CuFFTConvolution.cpp.o] Error 1
make[1]: *** [CMakeFiles/fbcunnlayers_cuda.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed installing.
mark@mark-All-Series:~/nn/fbtorch/fbnn/fbcunn$

**Comment by achansavang** [comment]
It seems that thpp was not installed properly...

**Comment by mszlazak** [comment]
Yup but i don't know why. Went through whole process many times except for installation of cuda driver 7.0. Do you know off hand where/when this gets installed? I am really new Linux and doing all this.  Please excuse the naivety.

**Comment by achansavang** [comment]
You could try installing thpp alone and see if there's any errors, take a look at https://raw.githubusercontent.com/soumith/fblualib/master/install_all.sh which installs thpp.

**Comment by mszlazak** [comment]
Thank you, that did something. It seemed to progress further along but encountered another problem with something it can't find related to Torch. Looks like I need to edit a cmake file. Some many copies of the particular one, I guess I got to find out which one. The end portion of the output is descriptive:

CMake Error at CMakeLists.txt:26 (FIND_PACKAGE):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/tmp/fblualib-build.AJTpjO/thpp/thpp/build/CMakeFiles/CMakeOutput.log".

Installing FBLuaLib

-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Folly: /usr/local/include  
-- Found Glog: /usr/include  
CMake Error at CMakeLists.txt:24 (FIND_PACKAGE):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/tmp/fblualib-build.AJTpjO/fblualib/fblualib/build/CMakeFiles/CMakeOutput.log".

All done!

**Comment by soumith** [comment]
sorry about this. I just fixed the fblualib install script so that this error does not happen now.
I made sure tagged versions of folly and fbthrift are installed, rather than trunk. I tested the install process on a fresh ubuntu 14.04 machine.

You'll have to redo the install process starting from this step:
https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-folly-fbthrift-thpp-and-fblualib

If you are having installation errors after retrying the install once more (after my fresh fixes), 
I can post the binaries here for Ubuntu 14.04 (they will be specific to ubuntu 14.04).

**Comment by SalemAmeen** [comment]
@soumith 
I think, it works. Thanks

**Comment by Tgaaly** [comment]
I have the same problem and I'm using updated Torch and scripts (as of 2 days ago). I followed the instructions to install fbcunn, ...etc. I get the same error. Can someone give the details of how to fix this? and where I can find the cmake file for Torch its looking for??

**Comment by soumith** [comment]
@Tgaaly what OS? Did you update torch or reinstall fresh? I want to make sure that there are no cached build files left over from the old install.

**Comment by Tgaaly** [comment]
I have Ubuntu 14.04. I updated torch. I'll try reinstalling fresh.

**Comment by Tgaaly** [comment]
I removed torch: rm -rf torch
and followed the steps of https://github.com/facebook/fbcunn/blob/master/INSTALL.md
when running 
```curl -sk https://raw.githubusercontent.com/soumith/fblualib/master/install_all.sh | bash -e```

I got the following error:
```
make[2]: Leaving directory `/tmp/fblualib-build.mfQ8yk/fbthrift/thrift'
make[1]: Leaving directory `/tmp/fblualib-build.mfQ8yk/fbthrift/thrift'
+ echo

+ echo 'Installing TH++'
Installing TH++
+ echo

+ cd /tmp/fblualib-build.mfQ8yk/thpp/thpp
+ ./build.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

**Comment by Tgaaly** [comment]
I resolved this issue with curl. Now I have the same error as above again.

```
CMake Error at CMakeLists.txt:24 (FIND_PACKAGE):
By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Torch", but
CMake did not find one.

Could not find a package configuration file provided by "Torch" with any of
the following names:

TorchConfig.cmake
torch-config.cmake
Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
"Torch_DIR" to a directory containing one of the above files. If "Torch"
provides a separate development package or SDK, be sure it has been
installed.

-- Configuring incomplete, errors occurred!
```

**Comment by mszlazak** [comment]
Thanks for trying Tgaaly. I haven't yet got to the point of re-installing fbcunn ... don't need to yet ... maybe I let this cook a bit while more issues are resolved. LOL.

**Comment by Tgaaly** [comment]
Another interesting problem:

when running ```sudo luarocks make rocks/nn-scm-1.rockspec```

I get:

```
Missing dependencies for nn:
torch >= 7.0


Error: Could not satisfy dependency: torch >= 7.0

```

**Comment by KangolHsu** [comment]
@Tgaaly you shoud not use ‘sudo’，because you sudo had not install torch，you install torch in current user dir
