### ISSUE TITLE
error while installing folly dependency on Ubuntu 14.04 EC2 Server

### ISSUE THREAD

**Issue by asampat3090** [facebook/fbcunn#63]
I've been trying to install the dependencies for fbcunn but am running into the following error below - I'm thinking it may be a compiler issue but I just opened up this ec2 instance and am not completely familiar with the system yet. Any ideas?

```
make[1]: Entering directory `/tmp/fblualib-build.c898EK/folly/folly'
Making all in .
make[2]: Entering directory `/tmp/fblualib-build.c898EK/folly/folly'
depbase=`echo Bits.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT Bits.lo -MD -MP -MF $depbase.Tpo -c -o Bits.lo Bits.cpp &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT Bits.lo -MD -MP -MF .deps/Bits.Tpo -c Bits.cpp  -fPIC -DPIC -o .libs/Bits.o
In file included from Bits.cpp:19:0:
./../folly/CpuId.h:160:19: sorry, unimplemented: non-static data member initializers
./../folly/CpuId.h:160:19: error: ISO C++ forbids in-class initialization of non-const static member 'f1c_'
./../folly/CpuId.h:161:19: sorry, unimplemented: non-static data member initializers
./../folly/CpuId.h:161:19: error: ISO C++ forbids in-class initialization of non-const static member 'f1d_'
./../folly/CpuId.h:162:19: sorry, unimplemented: non-static data member initializers
./../folly/CpuId.h:162:19: error: ISO C++ forbids in-class initialization of non-const static member 'f7b_'
./../folly/CpuId.h:163:19: sorry, unimplemented: non-static data member initializers
./../folly/CpuId.h:163:19: error: ISO C++ forbids in-class initialization of non-const static member 'f7c_'
make[2]: *** [Bits.lo] Error 1
make[2]: Leaving directory `/tmp/fblualib-build.c898EK/folly/folly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/fblualib-build.c898EK/folly/folly'
make: *** [all] Error 2
```

**Comment by soumith** [comment]
sorry about this. I just fixed the fblualib install script so that this error does not happen now.
I made sure tagged versions of folly and fbthrift are installed, rather than trunk. I tested the install process on a fresh ubuntu 14.04 machine.

You'll have to redo the install process starting from this step:
https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-folly-fbthrift-thpp-and-fblualib

If you are having installation errors after retrying the install once more (after my fresh fixes), 
I can post the binaries here for Ubuntu 14.04 (they will be specific to ubuntu 14.04).

**Comment by mrastegari** [comment]
I have the same issue.  

libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT Bits.lo -MD -MP -MF .deps/Bits.Tpo -c Bits.cpp  -fPIC -DPIC -o .libs/Bits.o
In file included from Bits.cpp:19:0:
./../folly/CpuId.h:160:19: sorry, unimplemented: non-static data member initializers
./../folly/CpuId.h:160:19: error: ISO C++ forbids in-class initialization of non-const static member 'f1c_'
./../folly/CpuId.h:161:19: sorry, unimplemented: non-static data member initializers
./../folly/CpuId.h:161:19: error: ISO C++ forbids in-class initialization of non-const static member 'f1d_'
./../folly/CpuId.h:162:19: sorry, unimplemented: non-static data member initializers
./../folly/CpuId.h:162:19: error: ISO C++ forbids in-class initialization of non-const static member 'f7b_'
./../folly/CpuId.h:163:19: sorry, unimplemented: non-static data member initializers
./../folly/CpuId.h:163:19: error: ISO C++ forbids in-class initialization of non-const static member 'f7c_'
make[2]: *** [Bits.lo] Error 1
make[2]: Leaving directory `/tmp/fblualib-build.JycSeo/folly/folly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/fblualib-build.JycSeo/folly/folly'
make: *** [all] Error 2
