### ISSUE TITLE
Compile error with fbcunn/fft

### ISSUE THREAD

**Issue by himerope** [facebook/fbcunn#67]
I'm building fbcunn on a new Ubuntu 14.04.2 installation.  The g++ version is 4.8.4.  Aside from a ton of warnings about non-standard code, my build is failing compiling the fft part of fbcunn.  I'm attaching the first few errors below.  I read through the install docs, but I didn't see any mention of specific g++ versions required.  Is there one?  I originally tried to compile this with the Intel compilers, but it failed hard and fast. 

Chuck

/home/fleming/torch/nn/fbcunn/src/fft/SpatialConvolutionCuFFT.cpp(551): error: qualified name is not allowed
    CuFFTConvolution conv(ConvolutionPass(ConvolutionPass::kUpdateOutput));
                                          ^

/home/fleming/torch/nn/fbcunn/src/fft/SpatialConvolutionCuFFT.cpp(552): error: expression must have class type
    conv.withInputAndBuffers(
    ^

/home/fleming/torch/nn/fbcunn/src/fft/SpatialConvolutionCuFFT.cpp(562): error: no instance of overloaded function "facebook::deeplearning::torch::CuFFTConvolution_UpdateOutput" matches the argument list
            argument types are: (THCState *, facebook::deeplearning::torch::CuFFTConvolution (*)(facebook::deeplearning::torch::ConvolutionPass), THCudaTensor *, THCudaTensor *)
    CuFFTConvolution_UpdateOutput(state, &conv, oTmp, bias);
    ^

**Comment by soumith** [comment]
hi, I just built it on ubuntu 14.04 with gcc 4.8.2, weird that I see no errors.

sorry about this. I just fixed the fblualib install script so that this error does not happen now.
You'll have to redo the install process starting from this step:

https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-folly-fbthrift-thpp-and-fblualib
