### ISSUE TITLE
Can I omit the process finding the best cufft and fbfft result?

### ISSUE THREAD

**Issue by Jeongseob** [facebook/fbcunn#69]
Hi,

Currently, I am trying to use fbcunn on AlexNet. When I use fbcunn, the warning messages are produced like below. I am not sure, but fbcunn dynamically evaluates which function provides the best performance. Is there a way to skip this step? In addition, it seems like that due to the logging, the stdout is not written to the file when I use 'cmd:log' from [cmdline](https://github.com/torch/torch7/blob/master/doc/cmdline.md).

'''
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0701 15:43:43.970839   754 SpatialConvolutionCuFFTTuner.cpp:160] START exploring FFT perf for pass = updateOutput     (b x p x f) = 128x96x256 (input rows x cols) = 31x31 (filter rows x cols) = 5x5 (common rows x cols) = 31x31
I0701 15:43:46.437228   754 SpatialConvolutionCuFFTTuner.cpp:115] Found best cufft result   Buffer=580.91M strategy = (Many cuFFT) (b x p x f) = 128x96x256 (input rows x cols) = 31x31 (filter rows x cols) = 5x5 (common rows x co
ls) = 32x32  GReductions(virtual fmas)/s = 3798.16  time = 19.90ms
I0701 15:43:46.437304   754 SpatialConvolutionCuFFTTuner.cpp:119] Found best fbfft result   Buffer=430.96M strategy = (Many FBFFT) (b x p x f) = 128x96x256 (input rows x cols) = 31x31 (filter rows x cols) = 5x5 (common rows x co
ls) = 32x32  GReductions(virtual fmas)/s = 4824.97  time = 15.66ms
I0701 15:43:46.437317   754 SpatialConvolutionCuFFTTuner.cpp:166] Found best result   Buffer=430.96M strategy = (Many FBFFT) (b x p x f) = 128x96x256 (input rows x cols) = 31x31 (filter rows x cols) = 5x5 (common rows x cols) =
32x32  GReductions(virtual fmas)/s = 4824.97  time = 15.66ms
I0701 15:43:46.437341   754 SpatialConvolutionCuFFTTuner.cpp:160] START exploring FFT perf for pass = updateGradInput  (b x p x f) = 128x96x256 (input rows x cols) = 31x31 (filter rows x cols) = 5x5 (common rows x cols) = 31x31
'''

**Comment by Jeongseob** [comment]
When I dynamically load the 'fbcunn' during runtime, the logging problem occurs. However, if I statically load the fbcunn, the logging works well without the problem. The reason why I want to dynamically load the fbcunn is that some machines does not install the fbcunn package. In such a case, I would like to use the cudnn.

**Comment by soumith** [comment]
hi, those messages are spit out using google's glog library, consult it's documentation on how to disable all logging, but I think you can set a simple environment variable to fix it.

**Comment by Jeongseob** [comment]
Hi,

Thank you for the reply. Except for the warning messages, I could not save the outputs into the file when I dynamically load fbcunn by using pcall function. After loading fbcunn, the file does not contain any outputs.
