### ISSUE TITLE
Error installing thpp: Wangle no such file or directory

### ISSUE THREAD

**Issue by tmensink** [facebook/fbcunn#70]
For me the install script didnt work. So installing each dependency by itself.

Folly is ok (at least it says so, and included in (/usr/local/include/folly)
Fbthrift seems ok.
But then thpp fails: after creating `build` directory and running `cmake` when running `make` I get the following error:

```
In file included from /usr/local/include/thrift/lib/cpp2/server/Cpp2ConnContext.h:22:0,
                 from /home/downloads/fbcunn/fb/thpp/thpp/build/thpp/if/gen-cpp2/Tensor_types.tcc:15,
                 from /home/downloads/fbcunn/fb/thpp/thpp/build/thpp/if/gen-cpp2/Tensor_types.cpp:9:
/usr/local/include/thrift/lib/cpp/concurrency/ThreadManager.h:28:43: fatal error: folly/wangle/concurrent/Codel.h: No such file or directory
 #include <folly/wangle/concurrent/Codel.h>
```

any help is appreciated. It seems that by installing folly not all files are copied correctly.

**Comment by soumith** [comment]
hi, sorry about this. I just fixed the fblualib install script so that this error does not happen now.
You'll have to redo the install process starting from this step:

https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-folly-fbthrift-thpp-and-fblualib

**Comment by tmensink** [comment]
Thanks!
