### ISSUE TITLE
Out of memory when running unmodified example on unmodified imagenet 2012 data.

### ISSUE THREAD

**Issue by bamos** [facebook/fbcunn#74]
Hi, I'm getting the following out of memory error with no traceback when running the example.
I've uploaded the full trace as gists: [no donkeys](https://gist.github.com/bamos/6190b6d33059097952a1), [2 donkeys](https://gist.github.com/bamos/669834fdd2b6f858ef2b).

```
$ th main.lua -nDonkeys 0

...

/home/bamos/torch/install/bin/luajit: not enough memory
```

With two donkeys, it gives the generic traceback:

```
/home/bamos/torch/install/bin/luajit: /home/bamos/torch/install/share/lua/5.1/threads/threads.lua:255:
[thread 1 endcallback] not enough memory
[thread 2 endcallback] not enough memory
[thread 1 endcallback] not enough memory
stack traceback:
        [C]: in function 'error'
        /home/bamos/torch/install/share/lua/5.1/threads/threads.lua:255: in function 'synchronize'
        /home/bamos/torch/install/share/lua/5.1/threads/threads.lua:196: in function 'addjob'
        /home/bamos/src/fbcunn/examples/imagenet/train.lua:99: in function 'train'
        main.lua:37: in main chunk
        [C]: in function 'dofile'
        ...amos/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00406670
```

Line 99 of `train.lua` is two callbacks:

```Lua
donkeys:addjob(
    -- the job callback (runs in data-worker thread)
    function()
      local inputs, labels = trainLoader:sample(opt.batchSize)
      return sendTensor(inputs), sendTensor(labels)
    end,
    -- the end callback (runs in the main thread)
    trainBatch
)
```

I get this same error for the `cudnn`, `fbcunn`, and `cunn` backends, and I've also tried decreasing `epochSize` and `batchSize` in hopes that the system will use less memory.

I thought this might be from a bad ulimit setting, but the following seems reasonable:

```
$ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-m: resident set size (kbytes)      unlimited
-u: processes                       514686
-n: file descriptors                1024
-l: locked-in-memory size (kbytes)  64
-v: address space (kbytes)          unlimited
-x: file locks                      unlimited
-i: pending signals                 514686
-q: bytes in POSIX msg queues       819200
-e: max nice                        0
-r: max rt priority                 0
-N 15:                              unlimited
```

My next guess is that I'm using slightly mismatched versions of something,
but I'm not sure how to easily get the versions of Torch libraries.
I'm using a standard 64-bit Ubuntu 14.04 installation with LuaJIT 2.1.0-alpha.

# Questions

1. Is there an easy way to dump all my Torch library versions for debugging things like this?
  The [install script](https://raw.githubusercontent.com/soumith/fblualib/master/install_all.sh)
  uses a temp directory, so the sources are difficult to find.
  
  If there's not an easy way to get the versions with Torch, maybe the installation scripts
  could write the versions to a permanent location?
2. How can I disable the huge arrays being printed to stdout?
3. Is there a VM or container image that's known to work well with this example?
4. I'd like to modify this code to use different models (some with gigabytes of parameters).
  With your experience, will Lua's memory limitations make this difficult?

**Comment by soumith** [comment]
Hi, this is very weird that the tensors are being printed to screen like that.

In fact, whatever your original error is, it is being masked by this "out of memory" error caused by the tensors being printed to screen.

Did you modify the example in any way?
Also, can you tell me more about your machine, what hardware it's running on?

**Comment by bamos** [comment]
Also, my machine has 64 GB of memory and a Tesla K40 GPU with 12 GB of memory, so I don't think I'm hitting any hardware limits.

Following's a screenshot as soon as I start the example:

![image](https://cloud.githubusercontent.com/assets/707462/8940492/4ce69c68-3538-11e5-9dca-ebd1f6e943ed.png)

The processes grow to a little over 2GB of resident memory before crashing every time.

**Comment by bamos** [comment]
Wow, thanks for the 2 minute response @soumith! Amazing.

+ Tensors are printed to the screen in every mode, and I couldn't find a print statement in the example code creating them. Maybe it's in a `*nn` library? Since you haven't seen this, I agree this may be my problem.
+ I'm using the unmodified https://github.com/facebook/fbcunn/commit/a0d2864674e7c3a759546eeb17ae185c456ee70d code.

Do you have any other suggestions? If not, I'll try to reinstall my entire Torch+dependency toolchain for this by hand by selecting the most recent release/tags -- I'll add a comment here with the versions.

**Comment by bamos** [comment]
Hi @soumith - I've shot myself in the foot here. :-)

A few weeks ago, I was playing around with `nn`'s implementation and added some print statements that I forgot about when trying to get the example working yesterday/today.
I just removed them and the example is working well.

**Comment by soumith** [comment]
so I've only seen such "print on crash" in very weird stack corruption settings (in multi-threaded mode), and this example should definitely not trigger any of those.

there's one thing I haven't updated in recent times, which is the getParamsByDevice branch. I just rebased and updated it. (I hope you are using it btw)

I'm setting up a fresh torch on a new machine, with latest (public) trunk of fbcunn and all. I'll let you know if I can reproduce this behavior in a few minutes.

In the meanwhile, try using this repo: https://github.com/soumith/imagenet-multiGPU.torch and let me know if you see the same behavior.

**Comment by soumith** [comment]
ah, cool, just was working on reproducing this, thankfully not needed anymore :)
