### ISSUE TITLE
Timing benchmarks of the Alexnet example on different backends (fbcunn/cudnn/cunn)

### ISSUE THREAD

**Issue by kindalu** [facebook/fbcunn#8]
Hi,

I ran the imagenet example code on GTX 980 (4GB Ram).
the training time on GPU per iters, printed like
Alexnet (batch size: 128) 
   fbcunn: 0.113s
   cudnn: 0.088s
   cunn: 0.58s

fbcunn is slower than cudnn, is this result reasonable?

---
And, if I run overfeat by fbcunn or cunn backend... it will crash (cudnn is ok.)
I thought it might be the 4GB ram issue. I changed the batchSize, then cunn works if batchSize < 32
But for fbcunn even if I changed the batchSize = 2-32, it still shows bad allocation error like this:

I0118 17:33:13.693274 27431 SpatialConvolutionCuFFTTuner.cpp:99] std::bad_alloc
F0118 17:33:13.693298 27431 SpatialConvolutionCuFFTTuner.cpp:102] Check failed: bestStrategy

Any suggestions?

---
PS: batchSize = 1 will show this on all backend library
[thread 1 callback] /fbcunn/examples/imagenet/train.lua:104: attempt to index local 'labels' (a number value)

**Comment by nicovaz** [comment]
Regarding the out of memory, the cuFFT based approach is very memory hungry atm.
We have a few things in the works to reduce the memory pressure but they will not be ready for some time.
The problem you experience is unrelated to batch sizes, it is most likely the expansion of the weights tensor that eats up all the memory.
In this case you should stick to the cudnn when you have 4GB memory.

HTH

**Comment by soumith** [comment]
@kindalu thanks for the feedback. 

> I ran the imagenet example code on GTX 980 (4GB Ram).
We have tuned our code for the Kepler architecture (Titan, K40), did not test it yet on Maxwell (GTX980). It is good to know some results.
However, on that note of timings, if you want to just clock the timing of the neural network properly, I suggest that you run the scripts with single-threaded data loading. It'll give more reliable numbers. For example
```bash
th main.lua -nDonkeys 0
```

wrt batchSize = 1, we have not supported that in the scripts, we need to change a few lines of code at a couple of places to support that.

**Comment by kindalu** [comment]
updated timing on GTX 980 (using -nDonkeys 0)
fbcunn:
![screen shot 2015-01-19 at 10 40 25 am](https://cloud.githubusercontent.com/assets/32716/5795392/0a3187d8-9fca-11e4-95b0-658d4661ea78.png)

cudnn:
![screen shot 2015-01-19 at 10 38 25 am](https://cloud.githubusercontent.com/assets/32716/5795394/1b0972d2-9fca-11e4-96b1-8537a5ef3378.png)

cunn:
![screen shot 2015-01-19 at 10 41 16 am](https://cloud.githubusercontent.com/assets/32716/5795398/2e6f84ce-9fca-11e4-9e9c-3d27fcac4262.png)
---
what is the result looks like on K40/Titan?

**Comment by antman1p** [comment]
Is there anyone who can lead me to some "beginner's" Resources?  I really
want to start learning AI and Nueral Networks and was excited to see this
released as open source, but haven't the slightest as to where to start.

**Comment by soumith** [comment]
@antman1p please post https://groups.google.com/forum/#!forum/torch7 for help. i am removing your comment because it is irrelevant to the discussion in this thread.

**Comment by soumith** [comment]
@kindalu two things.
The timing numbers were not at all accurate, as we were not synchronizing after each mini-batch.
With this commit:
https://github.com/facebook/fbcunn/commit/46bc8882e427cbfaa6c2b1ae6edff1c92aeea61d

I have just corrected this.
So update your fbcunn (git pull), and post the numbers again.
I am now running the numbers on Tesla K40 and will post them in 5 minutes.

**Comment by soumith** [comment]
Here are detailed numbers:
NVIDIA Tesla K-40 (ECC: Off)

1-GPU Numbers
-------------
fbcunn
```
th main.lua -nDonkeys 0 -nGPU 1 -backend fbcunn
Epoch: [1][0/10000]     Time 8.282 Err 6.9068 LR 1e-02
Epoch: [1][1/10000]     Time 0.402 Err 6.9064 LR 1e-02
Epoch: [1][2/10000]     Time 0.402 Err 6.9067 LR 1e-02
Epoch: [1][3/10000]     Time 0.399 Err 6.9070 LR 1e-02
Epoch: [1][4/10000]     Time 0.402 Err 6.9077 LR 1e-02
Epoch: [1][5/10000]     Time 0.401 Err 6.9082 LR 1e-02
```

cudnn (R1)
```
th main.lua -nDonkeys 0 -nGPU 1 -backend cudnn
Epoch: [1][0/10000]     Time 0.532 Err 6.9082 LR 1e-02
Epoch: [1][1/10000]     Time 0.534 Err 6.9099 LR 1e-02
Epoch: [1][2/10000]     Time 0.534 Err 6.9061 LR 1e-02
Epoch: [1][3/10000]     Time 0.536 Err 6.9074 LR 1e-02
Epoch: [1][4/10000]     Time 0.534 Err 6.9078 LR 1e-02
Epoch: [1][5/10000]     Time 0.535 Err 6.9079 LR 1e-02
```

cunn
```
th main.lua -nDonkeys 0 -nGPU 1 -backend cunn
Epoch: [1][0/10000]     Time 0.761 Err 6.9081 LR 1e-02
Epoch: [1][1/10000]     Time 0.759 Err 6.9087 LR 1e-02
Epoch: [1][2/10000]     Time 0.758 Err 6.9075 LR 1e-02
Epoch: [1][3/10000]     Time 0.758 Err 6.9081 LR 1e-02
Epoch: [1][4/10000]     Time 0.757 Err 6.9081 LR 1e-02
Epoch: [1][5/10000]     Time 0.759 Err 6.9060 LR 1e-02
```

2-GPU Numbers
-------------
fbcunn
```
th main.lua -nDonkeys 0 -nGPU 2 -backend fbcunn
Epoch: [1][0/10000]     Time 8.302 Err 6.9062 LR 1e-02
Epoch: [1][1/10000]     Time 0.276 Err 6.9067 LR 1e-02
Epoch: [1][2/10000]     Time 0.275 Err 6.9070 LR 1e-02
Epoch: [1][3/10000]     Time 0.277 Err 6.9074 LR 1e-02
Epoch: [1][4/10000]     Time 0.277 Err 6.9074 LR 1e-02
Epoch: [1][5/10000]     Time 0.276 Err 6.9077 LR 1e-02
```

cudnn
```
th main.lua -nDonkeys 0 -nGPU 2 -backend cudnn
Epoch: [1][0/10000]     Time 0.319 Err 6.9075 LR 1e-02
Epoch: [1][1/10000]     Time 0.316 Err 6.9084 LR 1e-02
Epoch: [1][2/10000]     Time 0.316 Err 6.9058 LR 1e-02
Epoch: [1][3/10000]     Time 0.316 Err 6.9079 LR 1e-02
Epoch: [1][4/10000]     Time 0.316 Err 6.9080 LR 1e-02
Epoch: [1][5/10000]     Time 0.315 Err 6.9081 LR 1e-02
```

cunn (does not work properly with 2-GPU because of NVIDIA CuBLAS Bug. They are fixing it in CUDA 7.0)
```
th main.lua -nDonkeys 0 -nGPU 2 -backend cunn
Epoch: [1][0/10000]     Time 0.736 Err 6.9073 LR 1e-02
Epoch: [1][1/10000]     Time 0.734 Err 6.9086 LR 1e-02
Epoch: [1][2/10000]     Time 0.734 Err 6.9082 LR 1e-02
Epoch: [1][3/10000]     Time 0.736 Err 6.9086 LR 1e-02
Epoch: [1][4/10000]     Time 0.735 Err 6.9080 LR 1e-02
Epoch: [1][5/10000]     Time 0.728 Err 6.9065 LR 1e-02
```

**Comment by kindalu** [comment]
Thanks for quick response!

Here is the new timing for GTX 980 after checkout the last commit 

th main.lua -data /storage/imagenet -nDonkeys 0 -nGPU 1 -backend fbcunn
![screen shot 2015-01-19 at 2 08 58 pm](https://cloud.githubusercontent.com/assets/32716/5796615/056565a0-9fe6-11e4-83fb-a3e255242fa7.png)

th main.lua -data /storage/imagenet -nDonkeys 0 -nGPU 1 -backend cudnn (R1)
![screen shot 2015-01-19 at 2 09 46 pm](https://cloud.githubusercontent.com/assets/32716/5796617/1d9d1c9e-9fe6-11e4-82fa-7f3c7e40f4e2.png)

th main.lua -data /storage/imagenet -nDonkeys 0 -nGPU 1 -backend cunn
![screen shot 2015-01-19 at 2 10 34 pm](https://cloud.githubusercontent.com/assets/32716/5796623/34104b5e-9fe6-11e4-9586-eaf6e267607b.png)

---
GTX 980 *2 on ASUS Z97-AR motherboard. (PCIE 3 x8/x8, connected with SLI)

th main.lua -data /storage/imagenet -nDonkeys 0 -nGPU 2 -backend fbcunn
![screen shot 2015-01-19 at 2 12 10 pm](https://cloud.githubusercontent.com/assets/32716/5796630/467462e4-9fe6-11e4-9fdd-8150f8b025b7.png)

th main.lua -data /storage/imagenet -nDonkeys 0 -nGPU 2 -backend cudnn (R1)
![screen shot 2015-01-19 at 2 20 49 pm](https://cloud.githubusercontent.com/assets/32716/5796647/7e11690e-9fe6-11e4-8596-299ebdd1aa15.png)

**Comment by soumith** [comment]
@kindalu thanks a lot for running the numbers. we will constantly improve our modules and push our changes to github, and if you ever encounter a use-case that has to do larger kernels (for example 13x13 kernels, or even extreme, lets say 128x128 kernels, like in [this paper](http://papers.nips.cc/paper/5573-joint-training-of-a-convolutional-network-and-a-graphical-model-for-human-pose-estimation), you will find that our FFT based convolutions are much faster than cudnn or anything else.

**Comment by orian** [comment]
Sorry for reviving, I've been hit by this today, I have a Network and data taking almost all memory of my GPU (Titan X). I've dig into the code and found a SpatialConvolutionCuFFT:explorePerformance. It looks it's using a cache. I thought that maybe it's possible to run a test run before I create a network and move the data to GPU?

I've tested:

     function explorePerformance(sccfft, input, nInputPlane, nOutputPlane, kW, kH)
        local batchSize = input:size(1);
        local filterSize = nOutputPlane -- THCudaTensor_size(NULL, params.weight, 0);
        local planeSize = nInputPlane --THCudaTensor_size(NULL, params.input, 1);
        local inputSizeRow = input:size(4) --THCudaTensor_size(NULL, params.input, 2);
        local inputSizeCol = input:size(3) -- THCudaTensor_size(NULL, params.input, 3);
        local weightSizeRow = kW  --THCudaTensor_size(NULL, params.weight, 2);
        local weightSizeCol = kH  --THCudaTensor_size(NULL, params.weight, 3);
        local outputSizeRow = (inputSizeRow - weightSizeRow) + 1;
        local outputSizeCol = (inputSizeCol - weightSizeCol) + 1;

        local batches = torch.Tensor({batchSize}):cuda()
        local filters = torch.Tensor({filterSize}):cuda()
        local planes = torch.Tensor({planeSize}):cuda()
        local inputRows = torch.Tensor({inputSizeRow}):cuda()
        local inputCols = torch.Tensor({inputSizeCol}):cuda()
        local kernelRows = torch.Tensor({weightSizeRow}):cuda()
        local kernelCols = torch.Tensor({weightSizeCol}):cuda()

        sccfft:explorePerformance(input, batches, filters, planes, inputRows,
            inputCols, kernelRows, kernelCols)
        sccfft:cleanupBuffers()
    end

    function CreateAndInit(input, nInputPlane, nOutputPlane, kW, kH)
        local net = nn.SpatialConvolutionCuFFT(nInputPlane,nOutputPlane,kW,kH,1,1)
        print('created')
        explorePerformance(net, input, nInputPlane, nOutputPlane, kW, kH)
        print('explored')
        return net
    end

But run with params below, it takes a long time:

    kW,kH=4,4
    nInputPlane=3
    nOutputPlane=3
    batchSize = 1
    weight,height = 1600,1600
    input = torch.Tensor(batchSize,kPlaneIn,weight,height):normal():cuda()
    net = nn.SpatialConvolutionCuFFT(nInputPlane,nOutputPlane,kW,kH,1,1)

**Comment by soumith** [comment]
hey @orian ,
could you try the sync branch: 
https://github.com/facebook/fbcunn/tree/sync
https://github.com/facebook/fbnn/tree/sync

We are in the process of cleaning up and pushing our latest changes, and we are targeting to do this before ICLR, but until then I temporarily pushed our latest code into the sync branch.

**Comment by soumith** [comment]
and we are moving the explorePerformance into lua land, after which you can do what you propose, i.e. explore before-hand and hard-code the paths.

**Comment by orian** [comment]
Thanks for hint, I've tried a sync. It shows a nice error msg. But during test I've found another error:
https://github.com/facebook/fbcunn/pull/44 can you merge?

**Comment by orian** [comment]
A bit of testing explorePerformace:
    kW	kH	iW	iH	time
    3	4	200	200	1.0675122300784m  
    3	5	200	200	1.1500549991926m  
    3	7	200	200	1.2289401849111m  
    3	8	200	200	1.2705718994141m  
    3	9	200	200	1.0359412670135m  
    3	10	200	200	1.081918768088m  
    3	11	200	200	1.1548316319784m  
    3	12	200	200	1.1676102161407m  
    3	13	200	200	1.2464199701945m
    3	14	200	200	1.5197109500567m
    3	15	200	200	1.0898248831431m  
    3	16	200	200	1.1229116002719m  
    3	17	200	200	1.1760312994321m
    
    3	30	200	200	1.1351620475451m  
    3	30	400	400	5.7949138482412m
    
    3	30	800	800	19.869072401524m
    3	30	1024	1024	9.2653200626373s
    3	30	1600	1600	36.637588977814s  

I've also monitored a GPU memory usage, I think it's loosing a memory somewhat (dangling pointers? setting globals?). After removing all objects and running `collectgarbage`, the GPU memory usage decreases only slightly, I will experiment a bit more and report further.
