### ISSUE TITLE
 tensor_serialization_test fails

### ISSUE THREAD

**Issue by FredericGodin** [facebook/fbcunn#85]
Hi,

I'm installing Torch on a new machine and for some reason, I doesn't pass all tests.
At first it did but then I got another error further downstream which needed a reinstall according to this forum. Now it's stuck at an error earlier in the installation process....

I reinstalled everything already a couple of times but it doesn't go away.
Maybe I didn't remove everything properly?

Thx!

Fréderic

    Linking CXX executable tensor_serialization_test
    [ 92%] Built target tensor_serialization_test
    Scanning dependencies of target tensor_test
    [100%] Building CXX object test/CMakeFiles/tensor_test.dir/TensorTest.cpp.o
    Linking CXX executable tensor_test
    [100%] Built target tensor_test
    Test project /tmp/fblualib-build.GO9rkm/thpp/thpp/build
        Start 1: storage_test
    1/3 Test #1: storage_test .....................   Passed    0.00 sec
        Start 2: tensor_test
    2/3 Test #2: tensor_test ......................   Passed    0.17 sec
        Start 3: tensor_serialization_test
    3/3 Test #3: tensor_serialization_test ........***Failed    0.03 sec

    67% tests passed, 1 tests failed out of 3

    Total Test time (real) =   0.21 sec

    The following tests FAILED:
          3 - tensor_serialization_test (Failed)
    Errors while running CTest

**Comment by soumith** [comment]
@FredericGodin unless you care about thrift serialization of tensors using fb.thrift, you can ignore this failure.

**Comment by FredericGodin** [comment]
Hi Soumith,

Thx for the confirmation!
Indeed, I ignored the error and adapted the script.
Torch is running fine for now.

Best,

Fréderic
