### ISSUE TITLE
Errors of running the ImageNet example.Help!

### ISSUE THREAD

**Issue by dazhenseu** [facebook/fbcunn#89]
I ran the ImageNet example, but it prompted an error of" gm (GraphicsMagick) binary not found, please install ", then I installed gm by "luarocks install gm" ,as a result ,the example stil cannot run! 
   In addtion, although the procedure at first ignore the error mentioned above, later, the procedure promted another error:[thread 2 callback] ...hen/torch/install/share/lua/5.1/graphicsmagick/Image.lua:378: magick.Image: error loading image: Unable to open file(/media/dazhen/experiment/ImageNetDataset/train/n02536864/n02536864_21158.JPE/media/dazhen/experiment/ImageNetDataset/train/n02536864/n02536864_21160.JPE...etc.
  Anyone knows how can I fix it?

**Comment by soumith** [comment]
answered elsewhere.

**Comment by dazhenseu** [comment]
yeah...someone answered first half of my question, thanks for him! But, after I installed gm well, it stll prompt"Unable to open file(/media/dazhen/experiment/ImageNetDataset/train/n02536864/n02536864_21158.JPE/media/dazhen/experiment/ImageNetDataset/train/n02536864/n02536864_21160.JPE...etc." It's very strange...and I stil don't know why..=_=

**Comment by soumith** [comment]
@dazhenseu this is strange. I suspect that your execution of this line:
https://github.com/facebook/fbcunn/blob/master/examples/imagenet/dataset.lua#L187-L189

is producing incorrect maxLength, making the rest of the script fail.

What OS / Version are you on? what is the version of your "wc" and "find" utilities?

**Comment by dazhenseu** [comment]
I was on Ubuntu 14.04. And the version of my "wc" and "find" utilities are GNU 8.21 and GNU 4.4.2 respectively. By the way, the procedure script and the data are not in the same place.

**Comment by dazhenseu** [comment]
ur...It works, mybe I know the reason, the path name I wrote has someting wrong----I mixed it up with my old folder.It's really careless of me...Anyway, thank you for your kindness!
