### ISSUE TITLE
Error on require 'logroll'

### ISSUE THREAD

**Issue by rudrapoudel** [facebook/fbcunn#9]
Hi there,

I am able to install fbcunn in one Ubuntu 14.x system. However, when I have installed 'logroll' package and tried to use it. I am getting following error. Please not that 'logroll' is working fine in my other workstations. So, I thought this would be the right place to post the issue.

th> require 'logroll'
...raries/torch-distro/install/share/lua/5.1/trepl/init.lua:319: loop or previous error loading module 'logroll'
stack traceback:
	[C]: in function 'error'
	...raries/torch-distro/install/share/lua/5.1/trepl/init.lua:319: in function 'require'
	[string "require 'logroll'"]:1: in main chunk
	[C]: in function 'xpcall'
	...raries/torch-distro/install/share/lua/5.1/trepl/init.lua:588: in function 'repl'
	...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406170

**Comment by soumith** [comment]
Give us the log for the command:
luajit -llogroll

**Comment by rudrapoudel** [comment]
rp14@bioeng079-pc:~/rudra/projects/imagenet$ luajit -llogroll
luajit: ...libraries/torch-distro/install/share/lua/5.1/fn/init.lua:1: module 'util' not found:
	no field package.preload['util']
	no file './util.lua'
	no file '/home/rp14/libraries/torch-distro/install/share/luajit-2.1.0-alpha/util.lua'
	no file '/usr/local/share/lua/5.1/util.lua'
	no file '/usr/local/share/lua/5.1/util/init.lua'
	no file '/home/rp14/libraries/torch-distro/install/share/lua/5.1/util.lua'
	no file '/home/rp14/libraries/torch-distro/install/share/lua/5.1/util/init.lua'
	no file './util.so'
	no file '/usr/local/lib/lua/5.1/util.so'
	no file '/home/rp14/libraries/torch-distro/install/lib/lua/5.1/util.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	...libraries/torch-distro/install/share/lua/5.1/fn/init.lua:1: in main chunk
	[C]: in function 'require'
	...ries/torch-distro/install/share/lua/5.1/logroll/init.lua:6: in main chunk
	[C]: at 0x0046a370
	[C]: at 0x00406170

**Comment by soumith** [comment]
i dont see any reason why this is related to fbcunn/fblualib. logroll is not able to find the "util" module, did you install that?

**Comment by rudrapoudel** [comment]
Hi Soumith,

Sorry, I didn't install the "util" separately and that was the problem. Now, solved.

Thank you once again!
