### ISSUE TITLE
ImageNet example crash after updating two packages?

### ISSUE THREAD

**Issue by dazhenseu** [facebook/fbcunn#90]
Hi~
 After I updated cunn and cutorch, the ImageNet example in fbcunn/examples/ImageNet cannot run, but before I updated these two packages, the example could run.The error is :
==> Converting model to CUDA
/home/dazhen/torch/install/bin/luajit: symbol lookup error: /home/dazhen/torch/install/lib/libTHC.so: undefined symbol: THAtomicAddLong 
How can I fix it?

**Comment by soumith** [comment]
@dazhenseu update the torch and nn packages as well.

luarocks install torch
luarocks install nn
luarocks install cutorch
luarocks install cunn

**Comment by soumith** [comment]
Also, to get started, I'd suggest going with https://github.com/soumith/imagenet-multiGPU.torch

I'll remove this one soon.

**Comment by dazhenseu** [comment]
thanks, it works
